### ISSUE TITLE
Unable to open a test DMG file created from a mac system 

### ISSUE THREAD

**Issue by vusarath** [libyal/libfsapfs#11]
This is issue is same as  #6 . But i followed the documentation which you provided their in the description and created a APFS dmg file of 100mb. I Created both non encrypted and Encrypted Dmg imaged from mac book air 
Both failed to open i used 

fsapfsinfo.exe -H D:\Resource\UnEcrypted.dmg
fsapfsinfo 20191104

Unable to open: D:\Resource\UnEcrypted.dmg.
libfsapfs_container_superblock_read_data: invalid object type: 0x00000000.
libfsapfs_container_superblock_read_file_io_handle: unable to read container superblock data.
libfsapfs_internal_container_open_read: unable to read container superblock at offset: 0 (0x00000000).
libfsapfs_container_open_file_io_handle: unable to read from file IO handle.
info_handle_open_input: unable to open input container.

**Comment by joachimmetz** [comment]
Per #6 could you indicate how you created the dmg?

This might help me determine which "disk image type" https://github.com/libyal/libmodi/blob/master/documentation/Mac%20OS%20disk%20image%20types.asciidoc#1-overview

**Comment by vusarath** [comment]
Thanks for your swift reply.
The dmg i created is not sparse or compressed.

I also tried creating dd Image of an apfs formated Pendrive but could't open that either

**Comment by joachimmetz** [comment]
Do you set offset to the partition that contains the APFS file system?

**Comment by joachimmetz** [comment]
No reply from original reporter, assuming question has been answered, closing issue.

**Comment by vusarath** [comment]
Sorry for the late delay 
Thanks it worked well able to mount and get info 
But when mounted it is only showing the root items

**Comment by joachimmetz** [comment]
> But when mounted it is only showing the root items

@vusarath you'll have to be more specific I cannot guess about your configuration and data? is the file system hierarchy of `fsapfsinfo -H` different than that of `fsapfsmount`? What does the debug output tell you? Also see: https://github.com/libyal/libfsapfs/wiki/Troubleshooting

Also note that this project indicates it is experimental.

**Comment by vusarath** [comment]
What does the debug output tell you? 
fsapfsmount.exe -v -f 0 -o 20480 D:\Resource\APFSCaseSensitive.dmg P:
mount_handle_set_file_system_index: invalid file system index value out of bounds.
Unsupported file system index defaulting to: all.
AllocationUnitSize: 512 SectorSize: 512
device opened
###QueryVolumeInfo -001
mounted: P: -> \Volume{d6cc17c5-170e-4085-bce7-964f1e9f5de9}
###Create 0000
CreateFile status = 0
###GetFileInfo 0000
        result =  0
  unknown type:54
        DispatchQueryInformation result =  c000000d
###GetFileInfo 0000
        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###QueryVolumeInfo 0000
###QueryVolumeInfo 0000
###Cleanup 0000
###Close 0000
###Create 0001
CreateFile status = 0
###GetFileInfo 0001
        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###QueryVolumeInfo 0001
###Cleanup 0001
###Close 0001
###Create 0002
CreateFile status = 0
###GetFileInfo 0002
        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###QueryVolumeInfo 0002
###Cleanup 0002
###Close 0002
###Create 0003
CreateFile status = 0
###GetFileInfo 0003
        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###QueryVolumeInfo 0003
###QueryVolumeInfo 0003
###Cleanup 0003
###Close 0003
###Create 0004
CreateFile status = 0
###GetFileInfo 0004
###Create 0005
###Create 0006
        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
CreateFile status = 0
CreateFile status = 0
###GetFileInfo 0004
###QueryVolumeInfo 0005
###GetFileInfo 0006
        result =  0
        FileNetworkOpenInformation
        DispatchQueryInformation result =  0
        result =  0
        FileBasicInformation
        DispatchQueryInformation result =  0
###QueryVolumeInfo 0005
###Cleanup 0004
###Cleanup 0006
###Cleanup 0005
###Close 0004
###Create 0007
###Close 0006
###Close 0005
mount_dokan_ZwCreateFile: unable to retrieve file entry for path: \.svn\wc.db.
CreateFile status = c0000034
###Create 0008
CreateFile status = 0
###GetFileInfo 0008
        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###GetFileInfo 0008
        result =  0
        FileNetworkOpenInformation
        DispatchQueryInformation result =  0
###Cleanup 0008
###Close 0008
###Create 0009
mount_dokan_ZwCreateFile: unable to retrieve file entry for path: \.svn\wc.db.
CreateFile status = c0000034
###Create 0010
CreateFile status = 0
###GetFileInfo 0010
        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###GetFileInfo 0010
        result =  0
        FileNetworkOpenInformation
        DispatchQueryInformation result =  0
###Cleanup 0010
###Close 0010
###Create 0011
mount_dokan_ZwCreateFile: unable to retrieve file entry for path: \.svn\wc.db.
CreateFile status = c0000034
###Create 0012
###Create 0012
CreateFile status = 0
CreateFile status = 0
###GetFileInfo 0012
###GetFileInfo 0013
        result =  0
        result =  0
        FileStandardInformation
        FileStandardInformation
        DispatchQueryInformation result =  0
        DispatchQueryInformation result =  0
###GetFileInfo 0013
###GetFileInfo 0012
        result =  0
        FileBasicInformation
        result =  0
        FileBasicInformation
        DispatchQueryInformation result =  0
        DispatchQueryInformation result =  0
###Cleanup 0013
###Cleanup 0012
###Close 0013
###Create 0014
###Close 0012
###Create 0014
CreateFile status = 0
CreateFile status = 0
###GetFileInfo 0014
###GetFileInfo 0015
        result =  0
        FileBasicInformation
        DispatchQueryInformation result =  0
        result =  0
###Cleanup 0014
        FileBasicInformation
        DispatchQueryInformation result =  0
###Close 0014
###Create 0016
###Cleanup 0015
CreateFile status = 0
###Close 0015
###Create 0017
###GetFileInfo 0016
CreateFile status = 0
        result =  0
        FileBasicInformation
        DispatchQueryInformation result =  0
###GetFileInfo 0017
###Cleanup 0016
        result =  0
        FileBasicInformation
        DispatchQueryInformation result =  0
###Close 0016
###Cleanup 0017
###Close 0017
###Create 0018
###Create 0018
CreateFile status = 0
mount_dokan_ZwCreateFile: unable to retrieve file entry for path: \desktop.ini.
###GetFileInfo 0018
CreateFile status = c0000034
        result =  0
        FileStandardInformation
###Create 0020
        DispatchQueryInformation result =  0
CreateFile status = 0
###GetFileInfo 0018
###GetFileInfo 0020
        result =  0
        FileBasicInformation
        DispatchQueryInformation result =  0
        result =  0
        FileBasicInformation
###Cleanup 0018
        DispatchQueryInformation result =  0
###Close 0018

**Comment by joachimmetz** [comment]
`mount_handle_set_file_system_index: invalid file system index value out of bounds.`

this indicates you should use `-f 1` instead of `-f 0` but is not fatal

`mount_dokan_ZwCreateFile: unable to retrieve file entry for path: \.svn\wc.db.`

indicates that it cannot retrieve this path however I'm not 100% if this path should exist?

**Comment by vusarath** [comment]
Thanks a lot
