### ISSUE TITLE
Debian build process throws error due to quilt source format

### ISSUE THREAD

**Issue by mnatter** [libyal/libfsapfs#16]
This is a super-helpful library! One issue I found, though, doing a Debian build on Ubuntu 19.10 according to your instructions [here](https://github.com/libyal/libfsapfs/wiki/Building#using-debian-package-tools-deb): received an error 'can't build with source format '3.0 (quilt)': no upstream tarball'.

Not sure if it is a quirk with my build environment, but found a workaround for a similar issue [here](https://github.com/Tarsnap/tarsnap/issues/205). By removing the file 'libfsapfs-20200416/dpkg/source/format' that specifies using quilt (of course before the 'cp -rf dpkg debian' step or in the debian folder after that step), the code appears to build just fine.

**Comment by joachimmetz** [comment]
This means dpkg-buildpackage cannot find ../libfsapfs-20200416.orig.tar.gz I'll add a note to the instructions.

**Comment by joachimmetz** [comment]
troubleshooting info added https://github.com/libyal/libfsapfs/wiki/Building#troubleshooting-1, closing issue
