### ISSUE TITLE
Checkpoint descriptor area offset larger than 4GB truncated to 32bit

### ISSUE THREAD

**Issue by rlei** [libyal/libfsapfs#18]
When testing libfsapfs with one of my larger SSDs (1TB), I noticed that checkpoint descriptor area offset calculation is still `uint32_t * uint32_t`, which results in an incorrect truncated 32bit offset. So I've just created a simple PR #17 to fix it. Could you have a look at it?

**Comment by joachimmetz** [comment]
Changes integrated into https://github.com/libyal/libfsapfs/commit/bfffe73536a232c321b341bda3ea6fcc955e840d

**Comment by joachimmetz** [comment]
@rlei let me know if that addresses the issue for you.

**Comment by joachimmetz** [comment]
No update from original reporter, closing issue
