### ISSUE TITLE
Unable to open source container

### ISSUE THREAD

**Issue by andreascyrilljoachim** [libyal/libfsapfs#20]
Hi.

My iMac crashed due to hardware issues with its graphic card.

In order to recover the data from my SSD (apfs file format) I run Ubuntu 20.04 from a USB-stick.
However I can not mount the drive with fsapfsmount:

```
sudo fsapfsmount -f 1 -o 409640 /dev/sdb2 /mnt/macos
fsapfsmount 20190210

Unable to open source container
libfsapfs_container_superblock_read_data: invalid object type: 0x00000000.
libfsapfs_container_superblock_read_file_io_handle: unable to read container superblock data.
libfsapfs_internal_container_open_read: unable to read container superblock at offset: 0 (0x00000000).
libfsapfs_container_open_file_io_handle: unable to read from file IO handle.
mount_handle_open: unable to open container.
```

I got the offset sector from gpart.

Using the -p and -r option gets the same response.

Do you have any idea what might be the problem?

Thanks in advance.

**Comment by joachimmetz** [comment]
Is your offset in bytes or in sectors? fsapfsmount needs bytes

**Comment by andreascyrilljoachim** [comment]
The offset was in sectors.

Running fdisk gets the sector size:

```
Festplatte /dev/sdb: 931,53 GiB, 1000204886016 Bytes, 1953525168 Sektoren
Festplattenmodell: Samsung SSD 850 
Einheiten: Sektoren von 1 * 512 = 512 Bytes
Sektorgröße (logisch/physikalisch): 512 Bytes / 512 Bytes
E/A-Größe (minimal/optimal): 512 Bytes / 512 Bytes
Festplattenbezeichnungstyp: gpt
Festplattenbezeichner: EDD6CC5D-691E-48A0-8F6D-ABF44DC306E7

Gerät      Anfang       Ende   Sektoren  Größe Typ
/dev/sdb1      40     409639     409600   200M EFI-System
/dev/sdb2  409640 1953525127 1953115488 931,3G unbekannt
```

So I multiplied the start sector by sector size and modified fsapfsmount:
```

fsapfsmount -f 1 -o 209735680 /dev/sdb2  /mnt/macos
fsapfsmount 20190210

Unable to open source container
libcfile_file_open_with_error_code: access denied to file: /dev/sdb2.
libcfile_file_open: unable to open file.
libbfio_file_open: unable to open file: /dev/sdb2.
libbfio_file_range_open: unable to open file IO handle.
libbfio_handle_open: unable to open handle.
libfsapfs_container_open_file_io_handle: unable to open file IO handle.
mount_handle_open: unable to open container.
```

**Comment by joachimmetz** [comment]
`libcfile_file_open_with_error_code: access denied to file: /dev/sdb2.` you need to run it with sudo, your user account has no permissions to access /dev/sdb2

**Comment by andreascyrilljoachim** [comment]
Sorry, rookie mistake.

Re-ran it as superuser:

```
sudo fsapfsmount -f 1 -o 209735680 -p XXX -r XXX  /dev/sdb2  /mnt/macos
fsapfsmount 20190210

Unable to open source container
libfsapfs_container_superblock_read_data: invalid object type: 0x00000000.
libfsapfs_container_superblock_read_file_io_handle: unable to read container superblock data.
libfsapfs_internal_container_open_read: unable to read container superblock at offset: 0 (0x00000000).
libfsapfs_container_open_file_io_handle: unable to read from file IO handle.
mount_handle_open: unable to open container.

```

**Comment by andreascyrilljoachim** [comment]
Thank you for your quick response btw. :)

**Comment by joachimmetz** [comment]
Drop the offset since /dev/sdb2 is (presumably) the start of your APFS container
the offset is only needed for the full disk /dev/sdb

**Comment by andreascyrilljoachim** [comment]
Sorry, here I go again:

```
sudo fsapfsmount -f 1 -p XXX -r XXX /dev/sdb2  /mnt/macos
fsapfsmount 20190210

Unable to open source container
libfsapfs_internal_container_open_read: missing checkpoint map block number.
libfsapfs_container_open_file_io_handle: unable to read from file IO handle.
mount_handle_open: unable to open container.

```
I get the same response when I omit option -p and -r.

When I use /dev/sdb instead of /dev/sdb2 as the volume to be mounted with offset-option it is the same:

```
sudo fsapfsmount -f 1 -o 209735680 -p sonvnqqv -r sonvnqqv /dev/sdb  /mnt/macos
fsapfsmount 20190210

Unable to open source container
libfsapfs_internal_container_open_read: missing checkpoint map block number.
libfsapfs_container_open_file_io_handle: unable to read from file IO handle.
mount_handle_open: unable to open container.
```

**Comment by joachimmetz** [comment]
> libfsapfs_internal_container_open_read: missing checkpoint map block number.

That looks like libfsapfs is at least able to find an APFS container, but is running into a data format issue.

https://github.com/libyal/libfsapfs/blob/bfffe73536a232c321b341bda3ea6fcc955e840d/libfsapfs/libfsapfs_container.c#L1368

I need to double check if the checkpoint map was necessary or if not, the code could be tweaked to ignore a missing checkpoint map

**Comment by andreascyrilljoachim** [comment]
Thanks for your help so far.

**Comment by alfonsrv** [comment]
@andreascyrilljoachim were you able to solve this in the meantime?

Or is there any update on the issue generally? Running into the same issue.

`sudo fsapfsmount -f 1 -p hunter42 /dev/sdb2  /mnt/`

**Comment by joachimmetz** [comment]
@alfonsrv the fact that you're running into the same warning / message does not mean it's the same issue.

**Comment by alfonsrv** [comment]
Oh, okay. I thought that's what error messages are for~

Trying to read a Time Machine backup created on Big Sur, M1-chip - is that using T2 encryption? Paragon also doesn't seem to work properly. Hope it helps.

**Comment by joachimmetz** [comment]
> Oh, okay. I thought that's what error messages are for~

the same message can have different causes, without the necessary context it is speculation.

> is that using T2 encryption

a T2 encrypted container is not supported, you can find if your system has a T2 in your system info

**Comment by elbamos** [comment]
I'm running into the same error message `libfsapfs_internal_container_open_read: missing checkpoint map block number.` trying to read an unencrypted apfs volume.

**Comment by joachimmetz** [comment]
@elbamos (1) hijacking an open issue is bad etiquette (2) specifically for your issue, use a more recent version of libfsapfs. 20190210 is very old

**Comment by joachimmetz** [comment]
Closing issue since looks like original question was answered

**Comment by andrewstec** [comment]
Once I reformatted my drive without the encryption set on AFPS, I could mount it on Linux no problem. I think the T2 encryption specified by @joachimmetz was the issue. 

I knew the password on my drive since I recently formatted it and had no luck mounting it. I got the same error as you.
