### ISSUE TITLE
Unable to mount volume inside container

### ISSUE THREAD

**Issue by laralar** [libyal/libfsapfs#23]
Hello, I am unable to mount the volume inside the container, currently I have w volumes, one not encrypted, and a second one encrypted.

fsapfstools % sudo ./fsapfsinfo -v /dev/disk3s2      
fsapfsinfo 20200416

Apple File System (APFS) information:

Container information:
	Identifier		: 080cf45d-976a-42cc-92d2-e12a3674e87b
	Number of volumes	: 2

Volume: 1 information:
	Identifier		: 652a004d-bc52-4a25-a7ca-a9fe6af7dc6c
	Name			: My Passport

Volume: 2 information:
	Identifier		: c0623fcb-e393-43bd-a20d-1ea3ad1b742b
	Name			: WD PR
	Is locked

How to mount a specific volume inside the container?

sudo ./fsapfsmount -v -p <PASSWORD> /dev/disk3s2  got
fsapfsmount 20200416

Unable to open source container
mount_handle_open: invalid volume index value out of bounds.

**Comment by joachimmetz** [comment]
Per https://github.com/libyal/libfsapfs/wiki/Mounting#mounting add `-f` for the file system you want to mount

**Comment by laralar** [comment]
I tried that.. but got the following:

sudo ./fsapfsmount -v -f 1 /dev/disk3s2  got  
fsapfsmount 20200416

No sub system to mount APFS format.

**Comment by laralar** [comment]
Still when I execute the info with -H I am getting all the respective file list of the volume

**Comment by joachimmetz** [comment]
> No sub system to mount APFS format.

Also explained here https://github.com/libyal/libfsapfs/wiki/Mounting, you did not build with fuse

**Comment by laralar** [comment]
Thanks. I don't get the error now but the following message:

sudo ./fsapfsmount -f 1 /dev/disk3s2 got
fsapfsmount 20200416

volicon: missing 'iconpath' option
Unable to create fuse handle.

fuse is installed now
configure:
Building:
   libcerror support:                           local
   libcthreads support:                         local
   libcdata support:                            local
   libclocale support:                          local
   libcnotify support:                          local
   libcsplit support:                           local
   libuna support:                              local
   libcfile support:                            local
   libcpath support:                            local
   libbfio support:                             local
   libfcache support:                           local
   libfdata support:                            local
   libfdatetime support:                        local
   libfguid support:                            local
   DEFLATE compression support:                 zlib
   libhmac support:                             local
   SHA256 support:                              local
   libcaes support:                             local
   AES-ECB support:                             local
   AES-XTS support:                             local
   FUSE support:                                libfuse

Features:
   Multi-threading support:                     pthread
   Wide character type support:                 no
   fsapfstools are build as static executables: no
   Python (pyfsapfs) support:                   no
   Verbose output:                              no
   Debug output:                                no

**Comment by joachimmetz** [comment]
That is MacOS/MacFuse specific issue `volicon: missing 'iconpath' option` you need to set iconpath https://github.com/osxfuse/osxfuse/wiki/Mount-options#volicon

**Comment by laralar** [comment]
Thanks for your help

I am executing the following and working:
root# ./fsapfsmount -X volicon=/Volumes/WD\ Unlocker/.VolumeIcon.icns -f 1 /dev/disk3s2 /Volumes/My\ Passport/
fsapfsmount 20200416

root# 

And now it seems to not get stuck or giving any error as before.  However, there is nothing in the mounted folder at first.

root# ls -la
ls: .: Device not configured
root#

After a while it shows the data.  I still can't get the data for the second encrypted volume.  Is this normal that it takes some time?


thanks for your help

**Comment by joachimmetz** [comment]
First of all per [README](https://github.com/libyal/libfsapfs/blob/master/README) this project is experimental. 

> After a while it shows the data. 

Second what is a "while" can you be specific? (Seconds, minutes, hours, days?)

> I still can't get the data for the second encrypted volume

Again can you be specific? What steps are you taking? Does the apfsinfo show you the volume is locked when you pass it the passphrase?

What is `/dev/disk3s2` ? Is that the APFS container ? (realize I do **NOT** have any insight into your configuration, explain more, be specific)

**Comment by laralar** [comment]
Yes.. thanks..  help is appreciated, and I know it is community and experimental.

Forget about the "while" maybe I was mistakingly looking into the encrypted folder. after umount /mount it shows the data immediately.


root# ./fsapfsmount -X volicon=/Volumes/WD\ Unlocker/.VolumeIcon.icns -f 2 /dev/disk3s2 /Volumes/WD\ PR/
fsapfsmount 20200416

Unable to unlock source container
 root# ./fsapfsmount -X volicon=/Volumes/WD\ Unlocker/.VolumeIcon.icns -f 2 -p PASSWORD /dev/disk3s2 /Volumes/WD\ PR/
fsapfsmount 20200416

root# ./fsapfsmount -X volicon=/Volumes/WD\ Unlocker/.VolumeIcon.icns -f 1 /dev/disk3s2 /Volumes/My\ Passport/
fsapfsmount 20200416

root# ls -la /Volumes/WD\ PR/
ls: : Device not configured
root# ls -la /Volumes/My\ Passport/
total 0
drwxrwxr-x@  2 root  wheel    0 Dec  5  2019 .
drwxr-xr-x  11 root  wheel  352 Jun 15 13:16 ..
...


root# ./fsapfsinfo /dev/disk3s2
fsapfsinfo 20200416

Apple File System (APFS) information:

Container information:
	Identifier		: 080cf45d-976a-42cc-92d2-e12a3674e87b
	Number of volumes	: 2

Volume: 1 information:
	Identifier		: 652a004d-bc52-4a25-a7ca-a9fe6af7dc6c
	Name			: My Passport


Volume: 2 information:
	Identifier		: c0623fcb-e393-43bd-a20d-1ea3ad1b742b
	Name			: WD PR
	Is locked

root# 

root# ./fsapfsinfo -p PASSWORD /dev/disk3s2
fsapfsinfo 20200416

Apple File System (APFS) information:

Container information:
	Identifier		: 080cf45d-976a-42cc-92d2-e12a3674e87b
	Number of volumes	: 2

Volume: 1 information:
	Identifier		: 652a004d-bc52-4a25-a7ca-a9fe6af7dc6c
	Name			: My Passport


Volume: 2 information:
	Identifier		: c0623fcb-e393-43bd-a20d-1ea3ad1b742b
	Name			: WD PR

Luiss-MBP-3:fsapfstools root#

**Comment by laralar** [comment]
diskutil apfs list

....


+-- Container ERROR -69808
    ======================
    APFS Container Reference:     disk4
    Size (Capacity Ceiling):      ERROR -69620
    Capacity In Use By Volumes:   ERROR -69620
    Capacity Not Allocated:       ERROR -69620
    |
    +-< Physical Store disk3s2 78CBE62E-EACD-42CC-B6F6-C2DE580CFED7
    |   -----------------------------------------------------------
    |   APFS Physical Store Disk:   disk3s2
    |   Size:                       1744155533312 B (1.7 TB)
    |
    +-> No Volumes
Luiss-MBP-3:fsapfstools root#

**Comment by joachimmetz** [comment]
> root# ls -la /Volumes/WD\ PR/
> ls: : Device not configured

You can try running fsapfsmount with debug output, that might indicate what is going on. For more information on enabling debug output see: https://github.com/libyal/libfsapfs/wiki/Troubleshooting#verbose-and-debug-output

**Comment by laralar** [comment]
Maybe some insight:
root# ./fsapfsinfo -H -f 1 /dev/disk3s2 
....
##### WORKS perfect.

### The following fails:

root# ./fsapfsinfo -H -f 2 -p PASSWORD /dev/disk3s2 
fsapfsinfo 20200416

Apple File System (APFS) information:

File system hierarchy:
Unable to print file system hierarchy.
libfsapfs_volume_get_root_directory: unable to retrieve root directory inode from file system B-tree.
info_handle_file_system_hierarchy_fprint: unable to retrieve root directory file entry from volume: 1.
root#

**Comment by joachimmetz** [comment]
You appear to be running into an unsupported data format condition. Enabling debug output will provide more detail.

**Comment by laralar** [comment]
ok.. thanks.

[APFS.log](https://github.com/libyal/libfsapfs/files/4779004/APFS.log)

**Comment by laralar** [comment]
ok.. thanks.. it is a huge file with all the information regarding my file listing and personal information.  Anything specific to look for?

It seems to be giving the listing properly, but at the end we have :

00000090: 20 34 38 30 4e cc 83 25  38 30 00 00                480N..% 80..

libfsapfs_file_system_btree_get_entry_from_node_by_identifier: retrieving B-tree entry identifier: 2, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 0, identifier: 929, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 1, identifier: 929, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 2, identifier: 930, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 3, identifier: 930, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 4, identifier: 931, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 5, identifier: 931, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 6, identifier: 932, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 7, identifier: 932, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 8, identifier: 933, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 9, identifier: 933, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 10, identifier: 934, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 11, identifier: 934, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 12, identifier: 935, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 13, identifier: 935, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 14, identifier: 936, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 15, identifier: 936, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 16, identifier: 937, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 17, identifier: 937, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 18, identifier: 938, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 19, identifier: 938, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 20, identifier: 939, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 21, identifier: 939, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 22, identifier: 940, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 23, identifier: 940, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 24, identifier: 941, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 25, identifier: 941, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 26, identifier: 942, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 27, identifier: 942, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 28, identifier: 943, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 29, identifier: 943, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 30, identifier: 944, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 31, identifier: 944, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 32, identifier: 945, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_inode_by_utf8_path: unable to retrieve entry from B-tree node.
libfsapfs_volume_get_file_entry_by_utf8_path: unable to retrieve inode from file system B-tree.
mount_file_system_get_file_entry_by_path: unable to retrieve file entry
mount_handle_get_file_entry_by_path: unable to retrieve file entry.
mount_fuse_getattr: unable to retrieve value for: /.

**Comment by joachimmetz** [comment]
> it is a huge file with all the information regarding my file listing and personal information. Anything specific to look for?

Yes best to sanitize the data before sharing. It is intended for debugging

It seems to be looking for file entry with ID 2 but cannot find it. What is the information around  the first occurrence of:
```
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: retrieving B-tree entry identifier: 2, data type: 0x3 (APFS_TYPE_INODE)
```

**Comment by laralar** [comment]
libfsapfs_btree_node_read_data: entry: 000 key data:
00000000: 01 00 00 00 00 00 00 90  0c 8c a6 ac 70 72 69 76   ........ ....priv
00000010: 61 74 65 2d 64 69 72 00                            ate-dir.

libfsapfs_btree_node_read_data: entry: 000 value data:
00000000: 4b 1a 00 00 00 00 00 00                            K.......

libfsapfs_btree_node_read_data: entry: 001 key data offset              : 0x0020 (block offset: 0x0098)
libfsapfs_btree_node_read_data: entry: 001 key data size                : 8
libfsapfs_btree_node_read_data: entry: 001 value data offset            : 0x0010 (block offset: 0x0fc8)
libfsapfs_btree_node_read_data: entry: 001 value data size              : 8

libfsapfs_btree_node_read_data: entry: 001 key data:
00000000: a1 03 00 00 00 00 00 30                            .......0

libfsapfs_btree_node_read_data: entry: 001 value data:
00000000: 4a 1a 00 00 00 00 00 00                            J.......

libfsapfs_file_system_btree_get_entry_from_node_by_identifier: retrieving B-tree entry identifier: 2, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 0, identifier: 1, data type: 0x9 (APFS_TYPE_DIR_REC)
libfsapfs_file_system_btree_get_entry_from_node_by_identifier: B-tree entry: 1, identifier: 929, data type: 0x3 (APFS_TYPE_INODE)
libfsapfs_file_system_btree_get_sub_node_block_number_from_entry: sub node object identifier: 6731
libfsapfs_object_map_btree_get_entry_from_node_by_identifier: retrieving B-tree entry identifier: 6731.
libfsapfs_object_map_btree_get_entry_from_node_by_identifier: B-tree entry: 0, identifier: 1038
libfsapfs_object_map_btree_get_entry_from_node_by_identifier: B-tree entry: 1, identifier: 6770
libfsapfs_object_map_btree_get_entry_by_identifier: B-tree sub node block number: 2056891
libfsapfs_object_map_btree_get_entry_from_node_by_identifier: retrieving B-tree entry identifier: 6731.
libfsapfs_object_map_btree_get_entry_from_node_by_identifier: B-tree entry: 0, identifier: 1038
libfsapfs_object_map_btree_get_entry_from_node_by_identifier: B-tree entry: 1, identifier: 1040
libfsapfs_object_map_btree_get_entry_from_node_by_identifier: B-tree entry: 2, identifier: 1066
libfsapfs_object_map_btree_get_entry_from_node_by_identifier: B-tree entry: 3, identifier: 6202
libfsapfs_object_map_btree_get_entry_from_node_by_identifier: B-tree entry: 4, identifier: 6240
libfsapfs_object_map_btree_get_entry_from_node_by_identifier: B-tree entry: 5, identifier: 6280
libfsapfs_object_map_btree_get_entry_from_node_by_identifier: B-tree entry: 6, identifier: 6291
libfsapfs_object_map_btree_get_entry_from_node_by_identifier: B-tree entry: 7, identifier: 6302
libfs

**Comment by joachimmetz** [comment]
So for some reason your file system B-tree does not correspond with what has been previously observed https://github.com/libyal/libfsapfs/blob/master/documentation/Apple%20File%20System%20(APFS).asciidoc#10-file-system

Any context about the file system you can provide:
* What version of MacOS was the volume/file system created on?
* What version of MacOS are you currently using?
* Is MacOS able to read the volume/file system?

**Comment by laralar** [comment]
Hmmm

I have done this with Catalina only,, not sure what specific sub version, but I definitely created it this year.

The volume was readable and I came across this post when hit wouldn't mount any more.

https://matt.sh/apfs-object-map-free-recovery

the issues described there are the same as mine except he is using an older version.

Right now MacOS can't mount/read the filesystem. it seems corrupted, although https://iboysoft.com can display the directory structure, and preview files from both the encrypted and the unencrypted volumes.

**Comment by joachimmetz** [comment]
It looks like a different type of file system corruption you are running into than the object map one

**Comment by laralar** [comment]
Thanks for your time.

Let's see what I can do.

**Comment by joachimmetz** [comment]
assuming question was answered, closing issue
