### ISSUE TITLE
Permission denied when trying to access disk device on Catalina as root

### ISSUE THREAD

**Issue by bimargulies** [libyal/libfsapfs#24]
I tried granting 'whole disk' and that didn't help.

```
sudo ./fsapfstools/fsapfsinfo -p "tPASSWORD" -H /dev/disk3s1

Unable to open: /dev/disk3s1.
libcfile_file_read_buffer_with_error_code: unable to read from file with error: Permission denied
libcfile_file_read_buffer: unable to read from file.
libbfio_file_read_buffer: unable to read from file: /dev/disk3s1.
libbfio_file_range_io_handle_read_buffer: unable to read from file IO handle.
libbfio_handle_read_buffer: unable to read from handle.
libfsapfs_container_superblock_read_file_io_handle: unable to read container superblock data.
libfsapfs_internal_container_open_read: unable to read container superblock at offset: 0 (0x00000000).
libfsapfs_container_open_file_io_handle: unable to read from file IO handle.
info_handle_open_input: unable to open input container.
bensonmargulies@puck libfsapfs-20200416 %
```

**Comment by joachimmetz** [comment]
What is `/dev/disk3s1` ? the APFS container? if so do you have it mounted?

**Comment by bimargulies** [comment]
I do not have it mounted. It's the device shown in disk utilities as
corresponding to the file system I need to fix.

**Comment by joachimmetz** [comment]
What does `diskutil apfs list` tell you about `/dev/disk3s1`? If its the APFS file system, you still have the APFS container mounter.

You'll need to fully unmount/detatch the APFS container (or whatever terminology MacOS is using) for it to allow access to the disk device.

**Comment by bimargulies** [comment]
+-> Volume disk3s1 D92C05C3-B0E1-43B5-9AEF-7895A1A43D19
        ---------------------------------------------------
        APFS Volume Disk (Role):   disk3s1 (No specific role)
        Name:                      8gbexternal (Case-insensitive)
        Mount Point:               Not Mounted
        Capacity Consumed:         14363189248 B (14.4 GB)
        FileVault:                 Yes (Unlocked)

**Comment by joachimmetz** [comment]
Based on your output I must conclude you have your APFS container (presumably `/dev/disk3` still mounted)

There should be a `Container Disk` or equiv as well

**Comment by joachimmetz** [comment]
No update from reporter assuming question was answered
