### ISSUE TITLE
Mapping of unknown values in volume

### ISSUE THREAD

**Issue by rickmark** [libyal/libfsapfs#29]
libfsapfs_volume_superblock_read_data: unknown32:
00000000: 73 74 6f 72 61 67 65 6b  69 74 64 20 28 31 36 37   storagek itd (167
00000010: 37 2e 34 30 2e 31 33 29  00 00 00 00 00 00 00 00   7.40.13) ........

libfsapfs_volume_superblock_read_data: unknown33				: 2020-08-22T00:35:03.428798492 UTC
libfsapfs_volume_superblock_read_data: unknown34				: 36
libfsapfs_volume_superblock_read_data: unknown35:
00000000: 61 70 66 73 5f 73 65 61  6c 76 6f 6c 75 6d 65 20   apfs_sea lvolume 
00000010: 28 31 36 37 37 2e 34 30  2e 31 33 29 00 00 00 00   (1677.40 .13)....

libfsapfs_volume_superblock_read_data: unknown36				: 2020-08-22T01:03:01.301082000 UTC
libfsapfs_volume_superblock_read_data: unknown37				: 243
libfsapfs_volume_superblock_read_data: unknown38:
00000000: 61 70 66 73 5f 6b 65 78  74 20 28 31 36 37 37 2e   apfs_kex t (1677.
00000010: 34 30 2e 31 33 29 00 00  00 00 00 00 00 00 00 00   40.13).. ........

`unknown32` is what created the volume
`unknown33-35` is what last wrote the volume/snapshot
`unknown38` is what last read the volume

**Comment by joachimmetz** [comment]
No additional input from original reporter, closing issue.
