### ISSUE TITLE
Support for Big Sur sealed snapshots

### ISSUE THREAD

**Issue by rickmark** [libyal/libfsapfs#30]
libfsapfs_volume_superblock_read_data: next document identifier			: 3
libfsapfs_volume_superblock_read_data: unknown60				: 0x00000001
libfsapfs_volume_superblock_read_data: unknown61				: 0x00000000
libfsapfs_volume_superblock_read_data: unknown62:
00000000: 00 00 00 00 00 00 00 00  10 00 00 00 ff ff ff 0f   ........ ........
00000010: f3 00 00 00 00 00 00 00  bd d0 00 00 00 00 00 00   ........ ........

Unable to print container information.
libfsapfs_volume_get_snapshot_by_index: unable to open snapshot: 0.
info_handle_volume_fprint: unable to retrieve snapshot: 0.
info_handle_container_fprint: unable to print volume: 4.

**Comment by joachimmetz** [comment]
Big Sur is not yet officially released, I'll make a note to look at its "sealed snapshots" functionality and if that affects this library. Closing this issue
