### ISSUE TITLE
How well does this compare to ...

### ISSUE THREAD

**Issue by TheAlienDrew** [libyal/libfsapfs#32]
... https://github.com/sgan81/apfs-fuse or https://github.com/linux-apfs/linux-apfs-oot ?

I've been using sgan81's apfs-fuse for the time being (testing), but I see that linux-apfs was updated more recently than the other, and then I came across your repo doing some research.

The biggest difference that I see about your repo is that it's updated more frequently than the both of them, so I want to know which one I should be better using (read-only access is all I need) for both encrypted and unencrypted drives.

**Comment by joachimmetz** [comment]
@TheAlienDrew "better" is very subjective and typically highly depends on the goal you are trying to accomplish. libfsapfs was created to research the APFS format and have a license that supports cumbersome-less integration of a library into other projects like [dfVFS](https://github.com/log2timeline/dfvfs).

**Comment by joachimmetz** [comment]
Also frequency of updates does not say anything without insight into what the updates are about.

**Comment by TheAlienDrew** [comment]
Yeah I understand what you mean about the frequency updates, that's why I'm not saying anyone is better than the other. I'm just trying to find the one that's most reliable and compatible when it comes to reading encrypted apfs drives.

**Comment by joachimmetz** [comment]
I can't speak for the other 2 implementations but libfsapfs supports encrypted APFS volumes that are backed by the software crypto provider. Hardware crypto provider backed encryption, like T2, are not supported.

[Here](https://github.com/libyal/libfsapfs/blob/master/README) you can find an overview of supported and non-supported format features currently known.

**Comment by joachimmetz** [comment]
@TheAlienDrew I assume the tumbsup is yours? github does not show this, and that it means your question has been answered and this issue can be closed?

**Comment by TheAlienDrew** [comment]
Yeah I'll go ahead and close it, I guess for now I'm going to keep using apfs-fuse.

**Comment by unphased** [comment]
> @TheAlienDrew I assume the thumbsup is yours? github does not show this, and that it means your question has been answered and this issue can be closed?

FWIW if you hover your mouse over the icon it does list the users (first few anyway) who added the reaction.

**Comment by joachimmetz** [comment]
> FWIW if you hover your mouse over the icon it does list the users (first few anyway) who added the reaction.

That does not work on my configuration. 

> I'm here because i've put a hard drive (which has an APFS partition used as possibly for time machine) that was in an external enclosure into my Ubuntu server and would like to read it without physically removing it again. Also curious which tool I should try to use...

IMHO this was answered in https://github.com/libyal/libfsapfs/issues/32#issuecomment-699438130
