### ISSUE TITLE
Unable to mount broken file system

### ISSUE THREAD

**Issue by lornally** [libyal/libfsapfs#34]
my external disk had been broken, so use libfsapfs mount it.
```sh
sudo fsapfsmount -X volicon=./Volume.icns /dev/disk3s2 got
```
after this, my got directory is disappear.
```sh
ll
ls: got: No such file or directory
total 40288
```
how can I find the disk just mounted? thank you:)

**Comment by joachimmetz** [comment]
First of all this project is experimental and not build with broken file system recovery in mind. You'll need to do the hard work there yourself. For troubleshooting see https://github.com/libyal/libfsapfs/wiki/Troubleshooting#verbose-and-debug-output

**Comment by lornally** [comment]
thank you, i will follow your link.
