### ISSUE TITLE
Does kernel version 5.4 (and higher) mean that support for T2 might be possible?

### ISSUE THREAD

**Issue by TheAlienDrew** [libyal/libfsapfs#36]
Or is there a lot more to the T2 chip encrypted drives that still needs to be reverse engineered to even get close?

**Comment by joachimmetz** [comment]
I have no idea what you are trying to ask here. 

If you want to understand the T2 at a high level I recommend to read Apple's white paper https://www.apple.com/ca/mac/docs/Apple_T2_Security_Chip_Overview.pdf

**Comment by TheAlienDrew** [comment]
What I basically mean is, I know that the hardware based encrypted is due to the T2 chip, and Linux kernel 5.4 at least brought support for interfacing with Apple's special NVMe drives that use the T2 chip a controller. Since support for the teacher chip has gotten that far, do you think it's the likely and the future for the hardware decryption to come into support?

**Comment by joachimmetz** [comment]
Not too familiar with the work on support of NVMe drive, I assume local T2 support might be possible at some point. That is a matter of interacting with the hardware.

However (based on analysis so far) decryption of an APFS woluke would still require the the same T2 chip that was used to encrypt it. Unless the container bag encryption key can be some how "extracted".

**Comment by TheAlienDrew** [comment]
Oh yeah I totally understand that. Personally I'd have no issue with that.

>

**Comment by joachimmetz** [comment]
> Personally I'd have no issue with that.

No issue with what extracting the key or requiring the same T2 chip? Your comment lacks context.

**Comment by TheAlienDrew** [comment]
For requiring the same T2 chip, my bad.

>

**Comment by joachimmetz** [comment]
I'll consider this question answered then, closing issue.
