### ISSUE TITLE
Unable to read corrupted file system

### ISSUE THREAD

**Issue by tt** [libyal/libfsapfs#38]
I have attempted using this library to recover data on a volume.

The disk has been in a drawer for so long that I'm not sure I remember how it got corrupted but I'm quite sure it was during its conversion to APFS.

Running First Aid in Disk Utility gives me this:

    Checking the fsroot tree.
    error: (oid 0x405) apfs_root: bt: invalid o_oid (0x41e)
    error: (oid 0x405) apfs_root: bt: invalid o_xid (0x143, expected 0x17b)
    error: (oid 0x405) apfs_root: bt: invalid o_type (0x10000003, expected 0x10000002)
    fsroot tree is invalid.

If I run `fsapfsinfo -p <password> -H -v` (or any of the other commands) with debugging logging enabled, I get the following:

    Unable to print file system hierarchy.
    libfsapfs_file_system_btree_get_root_node: invalid object type: 0x10000003.
    libfsapfs_file_system_btree_get_entry_by_identifier: unable to retrieve B-tree root node.
    libfsapfs_file_system_btree_get_inode_by_identifier: unable to retrieve entry from B-tree node.
    libfsapfs_volume_get_root_directory: unable to retrieve root directory inode from file system B-tree.
    info_handle_file_system_hierarchy_fprint: unable to retrieve root directory file entry from volume: 0.

The issue seems to be that it's trying to parse a sub node as a root node.

I have tried skipping some of the validation in libfsapfs_file_system_btree.c:

```patch
diff --git a/libfsapfs/libfsapfs_file_system_btree.c b/libfsapfs/libfsapfs_file_system_btree.c
index 9471ed1..1d52a79 100644
--- a/libfsapfs/libfsapfs_file_system_btree.c
+++ b/libfsapfs/libfsapfs_file_system_btree.c
@@ -545,7 +545,9 @@ int libfsapfs_file_system_btree_get_root_node(
 			goto on_error;
 		}
 		if( ( node->object_type != 0x00000002UL )
-		 && ( node->object_type != 0x10000002UL ) )
+		 && ( node->object_type != 0x10000002UL )
+		 && ( node->object_type != 0x00000003UL )
+		 && ( node->object_type != 0x10000003UL ) )
 		{
 			libcerror_error_set(
 			 error,
@@ -569,6 +571,8 @@ int libfsapfs_file_system_btree_get_root_node(
 
 			goto on_error;
 		}
+		if( ( node->object_type == 0x00000002UL ) || ( node->object_type == 0x10000002UL ) )
+		{
 		if( ( ( node->node_header->flags & 0x0001 ) == 0 )
 		 || ( ( node->node_header->flags & 0x0004 ) != 0 ) )
 		{
@@ -615,6 +619,7 @@ int libfsapfs_file_system_btree_get_root_node(
 
 			goto on_error;
 		}
+		}
 		if( libfcache_cache_set_value_by_identifier(
 		     file_system_btree->node_cache,
 		     0,
```

This is clearly not the right solution but it does allow outputting a subset of the files with `fsapfsinfo -p <password> -E all`. The first file entry has identifier 272 but I'm not sure this is necessarily an indicator of what's being skipped.

The library's handling of this is certainly consistent with the macOS behavior so I don't expect that this is a bug although I'm not sure. It seems there's definitely an opportunity to be more lenient.

That said, commercial tools seem to be able to show more files and if you have any pointers for how I might experiment with tweaking the parsing, I'm all ears.

**Comment by joachimmetz** [comment]
Per https://github.com/libyal/libfsapfs/blob/main/documentation/Apple%20File%20System%20(APFS).asciidoc#44-object-types 0x10000003 is used for a node not the root of the tree.

> That said, commercial tools seem to be able to show more files

This is not a commercial tool and all the work unfunded and best effort. 

> It seems there's definitely an opportunity to be more lenient

Being lenient has pros and cons. The primary goal of this library is to read APFS not to recover it.

> if you have any pointers for how I might experiment with tweaking the parsing

Carefully read the documentation first, you might be something possible with previous versions of the file system or come up with a recovery method.

**Comment by joachimmetz** [comment]
Closing issue

**Comment by tt** [comment]
> This is not a commercial tool and all the work unfunded and best effort.

I'm aware. I didn't mean that it therefore must be supported by you or this project. It was more as a test of feasibility to ensure the file system was not corrupted in a non-recoverable way.

> 0x10000003 is used for a node not the root of the tree.

I realize that but it's such a node that was being parsed by `libfsapfs_file_system_btree_get_root_node` so somehow the reference was bad. That's what was puzzling me.

I found a workaround for my case. I made `libfsapfs_file_system_btree_get_root_node` look for another root node if pointed at a sub node.

Interestingly, I then got another error from `fsapfsinfo -p <password> -E all -v`:

    Unable to print file entries.
    libfsapfs_file_system_btree_get_sub_node: invalid object type: 0x10000002.
    libfsapfs_file_system_btree_get_entry_by_identifier: unable to retrieve B-tree sub node from block: 50578.
    libfsapfs_file_system_btree_get_inode_by_identifier: unable to retrieve entry from B-tree node.
    libfsapfs_volume_get_file_entry_by_identifier: unable to retrieve inode: 0 from file system B-tree.
    info_handle_file_entries_fprint: unable to retrieve file entry: 0.

That's the inverse case. The pointer to what's supposed to be a sub node is actually a root node.

This is still quite confusing to me. The volume is encrypted so these are the references that macOS has written to disk and it's highly unlikely to be the result of corruption to the device itself.

Anyway, I swapped the two references in libfsapfs_file_system_btree.c:

[libfsapfs_file_system_btree_get_root_node](https://github.com/libyal/libfsapfs/blob/2dd44c0b0cecef8021ed0c7305da37acbdf7830c/libfsapfs/libfsapfs_file_system_btree.c#L383-L704):

        if( root_node_block_number == 0xc5c3 )
        {
                root_node_block_number = 0xc592;
        }

[libfsapfs_file_system_btree_get_sub_node](https://github.com/libyal/libfsapfs/blob/2dd44c0b0cecef8021ed0c7305da37acbdf7830c/libfsapfs/libfsapfs_file_system_btree.c#L706-L994):

        if( sub_node_block_number == 0xc592 )
        {
                sub_node_block_number = 0xc5c3;
        }

This allowed me to retrieve all the data. Of course there are no data consistency guarantees as I may have orphaned other nodes but I got what I wanted.

I hope this is helpful to anyone else searching for this problem in the future.

**Comment by joachimmetz** [comment]
> That's what was puzzling me.

most likely explanation, your file system is corrupted / left in a dirty state; the reference to the root of the tree is pointing to the wrong location

> The volume is encrypted so these are the references that macOS has written to disk and it's highly unlikely to be the result of corruption to the device itself.

Why is this highly unlikely? Based on other issues on this project, I would say APFS corruption happens fairly frequently.
