### ISSUE TITLE
Auto-mount on boot?

### ISSUE THREAD

**Issue by djcrawleravp** [libyal/libfsapfs#39]
N00b here,

Maybe this is a stupid question but... how can I configure fsapfsmount to mount my drive on boot?

thanks in advance!

**Comment by joachimmetz** [comment]
That depends on your operating system and out of scope of this project. fsapfsmount is a user space mount tool, not (operating) system level. For linux you might want to web search for "FUSE auto mount" e.g. https://www.linux.com/news/automounting-fuse-filesystems/
