### ISSUE TITLE
unable to read corrupt file system

### ISSUE THREAD

**Issue by loryxia** [libyal/libfsapfs#41]
Hello,

I have 4TB external hardware, somedays catalina can not identify it.

+-- Container disk3 BFA5F71E-5BA7-47FE-8FA9-9151A072B72B
    ====================================================
    APFS Container Reference:     disk3
    Size (Capacity Ceiling):      4000542842880 B (4.0 TB)
    Capacity In Use By Volumes:   3667478863872 B (3.7 TB) (91.7% used)
    Capacity Not Allocated:       333063979008 B (333.1 GB) (8.3% free)
    |
    +-< Physical Store disk2s2 C49FF986-DE05-4088-928F-220F313706AC
    |   -----------------------------------------------------------
    |   APFS Physical Store Disk:   disk2s2
    |   Size:                       4000542842880 B (4.0 TB)
    |
    +-> Volume disk3s1 998CE56A-5BDF-493F-95CE-AA7187AC61C1
        ---------------------------------------------------
        APFS Volume Disk (Role):   disk3s1 (No specific role)
        Name:                      4TB (Case-insensitive)
        Mount Point:               Not Mounted
        Capacity Consumed:         3657685364736 B (3.7 TB)
        FileVault:                 Yes (Unlocked)

i typed,

sudo ./fsapfstools/fsapfsinfo -p <password> -H /dev/disk3

fsapfsinfo 20210708

Apple File System (APFS) information:

File system hierarchy:
Unable to print file system hierarchy.
libfsapfs_file_system_btree_get_root_node: invalid object type: 0x10000003.
libfsapfs_file_system_btree_get_entry_by_identifier: unable to retrieve B-tree root node.
libfsapfs_file_system_btree_get_inode_by_identifier: unable to retrieve entry from B-tree node.
libfsapfs_volume_get_root_directory: unable to retrieve root directory inode from file system B-tree.
info_handle_file_system_hierarchy_fprint: unable to retrieve root directory file entry from volume: 0.

sudo ./fsapfstools/fsapfsinfo -p <password> -H /dev/disk2s2

fsapfsinfo 20210708

Apple File System (APFS) information:

File system hierarchy:
Unable to print file system hierarchy.
libfsapfs_file_system_btree_get_root_node: invalid object type: 0x10000003.
libfsapfs_file_system_btree_get_entry_by_identifier: unable to retrieve B-tree root node.
libfsapfs_file_system_btree_get_inode_by_identifier: unable to retrieve entry from B-tree node.
libfsapfs_volume_get_root_directory: unable to retrieve root directory inode from file system B-tree.
info_handle_file_system_hierarchy_fprint: unable to retrieve root directory file entry from volume: 0.

sudo ./fsapfstools/fsapfsinfo -p <password> -H /dev/disk3s1

libcfile_file_read_buffer_with_error_code: unable to read from file with error: Permission denied
libcfile_file_read_buffer: unable to read from file.
libbfio_file_io_handle_read_buffer: unable to read from file: /dev/disk3s1.
libbfio_file_range_io_handle_read_buffer: unable to read from file IO handle.
libbfio_internal_handle_read_buffer: unable to read from handle.
libbfio_handle_read_buffer_at_offset: unable to read buffer.
libfsapfs_container_superblock_read_file_io_handle: unable to read container superblock data at offset: 0 (0x00000000).
libfsapfs_internal_container_open_read: unable to read container superblock at offset: 0 (0x00000000).
libfsapfs_container_open_file_io_handle: unable to read from file IO handle.
info_handle_open_input: unable to open input container.

######

i just want to know, does this libfsapfs can resolve my hdd issue?

cause this happend , we know we should not use apfs in external hdd.

if this can not resolve this hdd issue, BTW, hwo do recovery my hdd data?

thank you all

**Comment by joachimmetz** [comment]
```
sudo ./fsapfstools/fsapfsinfo -p -H /dev/disk3s1
```

You cannot read from a mounted APFS container/volume device on MacOS, this is not related to hardware or libfsapfs but MacOS

```
libfsapfs_file_system_btree_get_root_node: invalid object type: 0x10000003.
```

Looks like your file system is corrupt: https://github.com/libyal/libfsapfs/blob/main/documentation/Apple%20File%20System%20(APFS).asciidoc#44-object-types

**Comment by joachimmetz** [comment]
> i just want to know, does this libfsapfs can resolve my hdd issue?

providing data recovery service is out of scope of this project, closing issue.
