### ISSUE TITLE
APFS object map recovery with libfsapfs ?

### ISSUE THREAD

**Issue by marcastel** [libyal/libfsapfs#43]
This IS NOT a `libfsapfs` issue<sup>(1)</sup>. But rather a question on how to use `libfsapfs` to recover, on macOS 11.2.3 (Intel), an encrypted APFS volume which neither `diskutil` nor `fsck` can recover.

My situation is similar to that discussed in #19.

1. DiskUtil reports a corrupted AFPS object map
    ```
    error: (oid 0x4f6fde) om: invalid o_type (0x40000002, expected 0x4000000b)
    error: verification/reading of the omap object failed: Illegal byte sequence
    ```

2. FSAPFSinfo reports access denied
    ```
    libcfile_file_read_buffer_with_error_code: unable to read from file with error: Permission denied
    ```

3. I can list the container
    ```
    +-> Volume disk7s2 8096BB9A-...
    |   ---------------------------------------------------
    |   APFS Volume Disk (Role):   disk7s2 (No specific role)
    |   Name:                      Briefcase (Case-sensitive)
    |   Mount Point:               Not Mounted
    |   Capacity Consumed:         3333190549504 B (3.3 TB)
    |   Sealed:                    No
    |   FileVault:                 Yes (Unlocked)
    ```

4. The free version<sup>(2)</sup> of [iBoySoft](https://iboysoft.com/) apparently sees all the files and folders. So the data is there.

5. My external USB (with the corrupted encrypted APFS volume) is correctly unmounted and I have installed [MacFUSE](https://github.com/osxfuse/osxfuse).

6. When I try to mount the disk rather than the volume, I get a consistent same error message as DiskUtil:
    ```
    sudo ./fsapfsmount -p 'passphrase' -v /dev/disk7 save-me
    fsapfsmount 20210424

    Unable to open source container
    libfsapfs_object_map_read_data: invalid object type: 0x40000002.
    libfsapfs_object_map_read_file_io_handle: unable to read object map data.
    libfsapfs_internal_container_open_read: unable to read object map at offset: 21323702272 (0x4f6fde000).
    libfsapfs_container_open_file_io_handle: unable to read from file IO handle.
    mount_handle_open: unable to open container.
    ```

Any help would be greatly appreciated.

<br><u>*Notes*</u>\
<sup>(1)</sup> If you are willing to open discussions on your GitHub repo, this would probably be a topic for discussion  :-)\
<sup>(2)</sup> I would rather fund an Open Source project.

**Comment by joachimmetz** [comment]
@marcastel at the moment this is not a goal of this project. To me the costs of the software you mention seem like a bargain, very low compared to the cost of the Apple hardware.
