### ISSUE TITLE
Unable to unlock source container

### ISSUE THREAD

**Issue by bertieuk** [libyal/libfsapfs#44]
Server: Ubuntu 20.04 LTS
Drive: Encrypted Mac OS APFS in USB caddy

fsapfsinfo & fsapfsmount installed from Ubuntu apt repository

_fsapfsinfo /dev/sdc2_ shows a container with 4 volumes; data, Preboot, Recovery & VM

_fsapfsinfo -f 1 -p <password> -H /dev/sdc2_ shows file structure 

_fsapfsmount -f 1 -p <password> /dev/sdc2 /mnt/ssd_ errors:

```
fsapfsmount 20190210

Unable to unlock source container
```

So I know the password is correct (if I change it fsapfsinfo fails) and can mount the Preboot and Recovery volumes and see them fine.

If the Ubuntu repo version is out-of-date, I'm happy to try upgrading / installing from source. Also, don't know how to check if they are APFS v1 or v2.

The drive works and boots in the Mac, I have 15 to clone/data transfer to a storage server and easier direct on the server if possible (I'll ultimately be installing them internally and not via USB caddy - I just wanted to get it working first)

Thanks!

**Comment by joachimmetz** [comment]
First try using a more recent version than 20190210

**Comment by bertieuk** [comment]
Removed the Ubuntu package, and followed the GNU complier build instructions, which gave me fsapfsmount 20210424

This worked and mounted it correctly :-)

**Comment by joachimmetz** [comment]
good to hear that it is working with the latest version, I'll consider this question answered and close this issue
