### ISSUE TITLE
How do I use configure --with-lib<something>?

### ISSUE THREAD

**Issue by PyBonnetainNesterenko** [libyal/libfsapfs#45]
Gentoo Linux here. Libcdata and libcerror are installed on the system, so we would like to configure libfsapfs to use them.

configure --with-libcdata aborts with :

checking for libcthreads... yes
checking whether to use search for libcdata in includedir and libdir or in the specified DIR, or no if to use local version... (cached) yes
configure: error: in /var/tmp/portage/app-forensics/libfsapfs-20210424/work/libfsapfs-20210424:
configure: error: no such directory: yes
See config.log for more details

Same error (« no such directory: yes ») if using --with-libcerror or, as a matter of fact, --with-libanything.

**Comment by joachimmetz** [comment]
1. First of all I do not recommend doing this, unless you have a really good understanding of implications of doing so
2. `--with-libcdata=PATH` is to be used with an installed version of libcdata not an extracted version of the source directory
3. add config.log for more details

**Comment by PyBonnetainNesterenko** [comment]
Cannot add logfile here, so put it on pastebin :
  https://pastebin.com/0S7AFBew

**Comment by joachimmetz** [comment]
So per `./configure --help` `--with-libcdata` requires a path argument and that path must point to an installed version (`make install`) of libcdata

**Comment by PyBonnetainNesterenko** [comment]
I thought the path was optional, and it would use the installed dir by default ?

**Comment by joachimmetz** [comment]
> I thought the path was optional, and it would use the installed dir by default ?

If a library is available as a shared library and the right version configure should pick up on that and you don't need `--with-libcdata` per configure:

```
  --with-libcdata[=DIR]   search for libcdata in includedir and libdir or in
                          the specified DIR, or no if to use local version
                          [default=auto-detect]
```

**Comment by PyBonnetainNesterenko** [comment]
Ok. We'll upgrade our build process.
Thanks.

**Comment by joachimmetz** [comment]
> Ok. We'll upgrade our build process.

I recommend not using a shared libcdata unless you really need to. This can have serious impact on performance due to thread locks you might not want

**Comment by PyBonnetainNesterenko** [comment]
Duly noted, and thanks again for all your work.
