### ISSUE TITLE
Unable to read the content - ls leads to Input/output error

### ISSUE THREAD

**Issue by srivattsan** [libyal/libfsapfs#46]
Hi,
I read through the other questions regarding "Unable to open source container". I was facing the same issue and was now able to get it mounted. However, when I perform 
`sudo ls MAC` 
(MAC is my mount point), I get  
`ls: reading directory 'MAC': Input/output error`
I followed your instructions to get the debug output which I am attaching below:

`libfsapfs_file_system_btree_get_attributes_from_leaf_node: B-tree entry: 4, identifier: 12885597002, data type: 0x8 (APFS_TYPE_FILE_EXTENT)`

`libfsapfs_attributes_get_data_stream: invalid attribute values.`
`libfsapfs_internal_file_entry_get_data_size: unable to retrieve data stream for compressed data extended attribute.`
`libfsapfs_file_entry_get_size: unable to determine data size.`
`mount_file_entry_get_size: unable to retrieve size from file entry.`
`mount_fuse_filldir: unable to retrieve file entry size.`
`mount_fuse_readdir: unable to set directory entry.`
`mount_fuse_releasedir: /`

I have cropped the output to only include the lines where it says there's an issue. 

To give an overview of my setup, I am running Ubuntu on a stick (without installing) on Macbook Pro. I was trying to upgrade my MacOS to Big Sur and ran into issues. I am currently unable to boot into my old OS as well. I ran disk verification and first aid through the disk utility and everything turned out fine. At this point, I just want to get the data out of the disk to an external drive, format everything and install Big Sur on my mac. Any help/suggestion on how to access the files using fsapfs tool will be really helpful! Please let me know if you require any other info. 

Output when I run fsinfo

`$ sudo fsapfsinfo /dev/sda2`
`fsapfsinfo 20210902`

`Apple File System (APFS) information:`

`Container information:`
`	Identifier			: 50611391-8854-4a9c-b224-931a82558251`
`	Number of volumes		: 5`

`Volume: 1 information:`
`	Identifier			: e9189288-4f52-3782-acb5-eafa8fff3818`
`	Name				: Macintosh HD - Data - Data - Data - Data - Data - Data - Data - Data - Data - Data`
`	Compatible features		: 0x00000012`
`		(NX_FEATURE_LCFD)`

`	Incompatible features		: 0x00000005`
`		(NX_INCOMPAT_VERSION1)`

`	Read-only compatible features	: 0x00000000`

`Volume: 2 information:`
`	Identifier			: 4ef85cc4-903e-4c8f-aff1-6ac07ffa156b`
`	Name				: Preboot`
`	Compatible features		: 0x00000002`
`		(NX_FEATURE_LCFD)`

`	Incompatible features		: 0x00000001`
`		(NX_INCOMPAT_VERSION1)`

`	Read-only compatible features	: 0x00000000`

Cropped other information for brevity. 

I used the command
`sudo fsapfsmount -f 1 -v /dev/sda2 MAC/`
to mount the SSD and pasted the verbose output in this question.

**Comment by joachimmetz** [comment]
Could you check https://github.com/libyal/libfsapfs/commit/ca3d05c317ed3c350b54b4e25661ca8d91b239f4 I think this issue should be addressed now
