### ISSUE TITLE
fsapfsmount: /Volumes/Test: No such file or directory

### ISSUE THREAD

**Issue by idandreyka** [libyal/libfsapfs#47]
I was able to list my folders & files from disk3 image using the next command:
`./fsapfstools/fsapfsinfo -p pass -H /dev/disk3`

I received a long output like this (seems like file names are correct):
>.... 
/{0f1e44a8-2509-3e85-af09-dfc30ce9b7ab}/usr/local/texlive/2017basic/texmf-var/xdvi
/{0f1e44a8-2509-3e85-af09-dfc30ce9b7ab}/usr/local/texlive/2017basic/texmf.cnf
/{0f1e44a8-2509-3e85-af09-dfc30ce9b7ab}/usr/local/texlive/2017basic/LICENSE.CTAN
....

Also, I was able to mount this my disk3: 
`sudo ./fsapfstools/fsapfsmount -X allow_root -p pass -f 1 /dev/disk3 /Volumes/Test  `

And then when I check "mount" in terminal I receive next result:

> /dev/disk1s5s1 on / (apfs, sealed, local, read-only, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk1s4 on /System/Volumes/VM (apfs, local, noexec, journaled, noatime, nobrowse)
/dev/disk1s2 on /System/Volumes/Preboot (apfs, local, journaled, nobrowse)
/dev/disk1s6 on /System/Volumes/Update (apfs, local, journaled, nobrowse)
/dev/disk1s1 on /System/Volumes/Data (apfs, local, journaled, nobrowse)
map auto_home on /System/Volumes/Data/home (autofs, automounted, nobrowse)
fsapfsmount@macfuse0 on /Volumes/Test (macfuse, synchronous)

I can't open /Volumes/Test directory and because "-bash: cd: /Volumes/Test: No such file or directory", also disk is not visible in finder or Disk Utility 

**How can I open "macfuse" mounted disk? Or at least restore my files back**

Im using BugSur 11.6 and libfsapfs-20210424
This is my diskutil output:
> diskutil apfs list
APFS Containers (2 found)
|
+-- Container disk1 57F2A2D6-FDDE-4A86-9B28-E0D62F741852
|   ====================================================
|   APFS Container Reference:     disk1
|   Size (Capacity Ceiling):      500068036608 B (500.1 GB)
|   Capacity In Use By Volumes:   278084947968 B (278.1 GB) (55.6% used)
|   Capacity Not Allocated:       221983088640 B (222.0 GB) (44.4% free)
|   |
|   +-< Physical Store disk0s2 5832B84E-B73C-47F7-A9AD-3579A3B0DFD9
|   |   -----------------------------------------------------------
|   |   APFS Physical Store Disk:   disk0s2
|   |   Size:                       500068036608 B (500.1 GB)
|   |
|   +-> Volume disk1s1 C0CF5EB9-F932-4DD1-9F70-E9DD2B31F082
|   |   ---------------------------------------------------
|   |   APFS Volume Disk (Role):   disk1s1 (Data)
|   |   Name:                      Macintosh HD - Data (Case-insensitive)
|   |   Mount Point:               /System/Volumes/Data
|   |   Capacity Consumed:         260043075584 B (260.0 GB)
|   |   Sealed:                    No
|   |   FileVault:                 No
|   |
|   +-> Volume disk1s2 7539C906-9530-4A29-86E6-A9F22695B506
|   |   ---------------------------------------------------
|   |   APFS Volume Disk (Role):   disk1s2 (Preboot)
|   |   Name:                      Preboot (Case-insensitive)
|   |   Mount Point:               /System/Volumes/Preboot
|   |   Capacity Consumed:         334757888 B (334.8 MB)
|   |   Sealed:                    No
|   |   FileVault:                 No
|   |
|   +-> Volume disk1s3 A4247636-59A8-4B7E-A23A-632E15AE8E5C
|   |   ---------------------------------------------------
|   |   APFS Volume Disk (Role):   disk1s3 (Recovery)
|   |   Name:                      Recovery (Case-insensitive)
|   |   Mount Point:               Not Mounted
|   |   Capacity Consumed:         1137700864 B (1.1 GB)
|   |   Sealed:                    No
|   |   FileVault:                 No
|   |
|   +-> Volume disk1s4 304868B8-6C7C-4E31-9A79-E2B1146CD1AF
|   |   ---------------------------------------------------
|   |   APFS Volume Disk (Role):   disk1s4 (VM)
|   |   Name:                      VM (Case-insensitive)
|   |   Mount Point:               /System/Volumes/VM
|   |   Capacity Consumed:         1074810880 B (1.1 GB)
|   |   Sealed:                    No
|   |   FileVault:                 No
|   |
|   +-> Volume disk1s5 8285866F-F87F-4BCC-9FDC-3535BBF0D5BD
|       ---------------------------------------------------
|       APFS Volume Disk (Role):   disk1s5 (System)
|       Name:                      Macintosh HD (Case-insensitive)
|       Mount Point:               Not Mounted
|       Capacity Consumed:         15332179968 B (15.3 GB)
|       Sealed:                    Broken
|       FileVault:                 No
|       |
|       Snapshot:                  63C48844-48E0-4B79-865F-AB09C9179379
|       Snapshot Disk:             disk1s5s1
|       Snapshot Mount Point:      /
|       Snapshot Sealed:           Yes
|
+-- Container ERROR -69808
    ======================
    APFS Container Reference:     disk3
    Size (Capacity Ceiling):      ERROR -69620
    Capacity In Use By Volumes:   ERROR -69620
    Capacity Not Allocated:       ERROR -69620
    |
    +-< Physical Store disk2 (No UUID)
    |   ------------------------------
    |   APFS Physical Store Disk:   disk2
    |   Size:                       200000118784 B (200.0 GB)
    |
    +-> No Volumes

Thank you for any suggestions!

**Comment by joachimmetz** [comment]
> I can't open /Volumes/Test directory and because "-bash: cd: /Volumes/Test: No such file or directory", also disk is not visible in finder or Disk Utility

You'll need to make sure `/Volumes/Test` exists as a directory before mounting

**Comment by idandreyka** [comment]
Thank you for your fast response

Of course I created this directory, first screenshot before running fsapfsmount:
<img width="657" alt="Screen Shot 2021-10-05 at 9 39 25 AM" src="https://user-images.githubusercontent.com/14205323/136034730-ba9078ea-e748-4971-aa8e-93fd83c2657a.png">

But after I run `sudo ./fsapfstools/fsapfsmount -X allow_root -p pass  -f 1 /dev/disk2 /Volumes/Test `, this folder disappears, you can still see it by running 'ls', I can still run 'umount /Volumes/Test' (after this folder will be removed from mount), but it is not accessible and not visible in finder... 
<img width="590" alt="Screen Shot 2021-10-05 at 9 48 03 AM" src="https://user-images.githubusercontent.com/14205323/136035818-4f8f3527-1a56-42bf-b952-7bae15d74b8e.png">
I tried multiple locations (including a new folder on desktop) but always the same behavior

**Comment by idandreyka** [comment]
Seems like it was an access issue.
To solve it you need to enter superuser mode: `sudo -s`
And after that, you will be able to enter to created folder and see all files.

Thanks again, @joachimmetz, how to buy you a coffee?

**Comment by joachimmetz** [comment]
> Thanks again, @joachimmetz, how to buy you a coffee?

noprob, I opt to donate it to a local charity

Seeing the question was answered, I'll close the issue
