### ISSUE TITLE
building on macos 12.0 beta gives an error

### ISSUE THREAD

**Issue by alexfs** [libyal/libfsapfs#48]
./configure
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

./configure --prefix=/usr/local --enable-python --with-pyprefix
configure: WARNING: unrecognized options: --enable-python, --with-pyprefix
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

Any advice?

**Comment by alexfs** [comment]
Attached, thank you. 

[config.log](https://github.com/libyal/libfsapfs/files/7294426/config.log)

**Comment by joachimmetz** [comment]
Looks like it can't find any compiler or necessary binutils/build utils:
```
CC=''
CFLAGS=''
CPP=''
CPPFLAGS=''
CXX=''
CXXFLAGS=''
DEFS=''
DPKG_DATE=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
EXEEXT=''
GREP=''
```

**Comment by alexfs** [comment]
Hmm...I do have xcode, xcode command line tools and brew installed. 
Xcode 13.0 beta 5

**Comment by joachimmetz** [comment]
No issues here building the source distribution package on Mac OS 12 beta 9 with XCode, closing this issue.
