### ISSUE TITLE
Unable to list files in specific folder: Input/output error

### ISSUE THREAD

**Issue by samangh** [libyal/libfsapfs#49]
Hi,

Thanks for your work.

I'm mounting a macOS Big Sur system partition. Mounting works fine and I can read most files, except the contents of the `Library` folder in the user home directory (e.g. `/Users/<user>/Library`).

I'm doing this as root. The partition was mounted using `fsapfsmount -f 1 -X allow_other /dev/sda2 /mnt/macOS`, and `mount` shows:

```
/dev/fuse on /mnt/macOS type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
```

This is the error I get:

```
# cd /mnt/macOS/Users/saman/Library
# ls
ls: reading directory '.': Input/output error
```

Reading other folders seems to work fine. Any idea how to fix or debug this?

**Comment by joachimmetz** [comment]
> Any idea how to fix or debug this?

https://github.com/libyal/libfsapfs/wiki/Troubleshooting#format-or-behavioral-errors

If you can share the debug output or a sample file that triggers the issue that would be helpful

**Comment by Climax777** [comment]
I have a very similar issue. Info works flawlessly but mount just gets stuck and my mounted folder is inaccessible:
```
ls: cannot access 'apple': Permission denied
total 12K
d?????????? ? ?    ?       ?            ? apple
```

My disk is encrypted. I did manage to get my image working a year ago, while still running ubuntu 21.04 or 21.10. I even copied the exact same command line:
`sudo fsapfsmount -f 1 -p REDACTED -v -o 209735680  /mnt/android/hikvision.img /media/apple`

The output of the info:
```
sudo fsapfsinfo -f 1 -p REDACTED -o 209735680  /mnt/android/hikvision.img                                                                                   9.2s  Sat 05 Feb 2022 09:43:49 PM SAST
fsapfsinfo 20220201

Apple File System (APFS) information:

Container information:
        Identifier                      : 75f18d43-d2b2-43e4-8780-8e8f05988006
        Number of volumes               : 1

Volume: 1 information:
        Identifier                      : ef49a42f-df56-4e50-bb17-67d71f18aa3a
        Name                            : MacExternal
        Compatible features             : 0x00000002
                (NX_FEATURE_LCFD)

        Incompatible features           : 0x00000001
                (NX_INCOMPAT_VERSION1)

        Read-only compatible features   : 0x00000000
```

Like I mentioned this worked last year on the exact same image. I even built from git now, and it didn't make a difference. 

I'm happy to send my debug logs, if you can provide a private upload option?

**Comment by joachimmetz** [comment]
@Climax777 are you sure you're not running into a fuse access limitation? If you mount it as root you need to access it as root unless you configure fuse to allow others

**Comment by joachimmetz** [comment]
Also original reporter never responded closing issue
