### ISSUE TITLE
Does libfsapfs support macFUSE?

### ISSUE THREAD

**Issue by Crush12999** [libyal/libfsapfs#50]
My MacOS version `12.1(21C52) Monterey`. Since my hard disk couldn't mount, I tried to mount and read it using libfsapfs.
But I ran into some problems with it, I was told when installing `OSXFuse` that the version did not work on my system,so the upgrade used `MacFuse`.
But after I successfully installed `MacFuse`, I tried to build libfsapfs using `CC="xcrun GCC "./configure`, and the last part of the log showed `FUSE Support: no`. 
`sudo ./fsapfsinfo -H /dev/disk4s5 > mylog.txt` is available to get my disk file tree. 
When I tried to mount it using `sudo ./fsapfsmount -f 1 /dev/disk4s5 mydisk`, I got an error: `No sub system to mount APFS format`.
I would like to ask you, libfsapfs does not support the latest MacFUSE, or do you have a good solution to my problem? thank you.

**Comment by joachimmetz** [comment]
Try passing `CPPFLAGS=-DFUSE_USE_VERSION=26` to configure, e.g. `./configure CPPFLAGS=-DFUSE_USE_VERSION=26`

**Comment by Crush12999** [comment]
Thank you very much for your help. I have solved the problem through your method.
