### ISSUE TITLE
Unable to compile on Mac OS Big Sur - libcaes related warnings

### ISSUE THREAD

**Issue by srjavabeans** [libyal/libfsapfs#51]
I'm trying to recover my files from a broken apfs partition returning error 49218

I got these compilation errors, any clue?

libcaes_context.c:387:6: error: use of undeclared identifier 'libcaes_tables_initialized'; did you mean 'libcaes_context_initialize'?
        if( libcaes_tables_initialized == 0 )
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
            libcaes_context_initialize
libcaes_context.c:258:5: note: 'libcaes_context_initialize' declared here
int libcaes_context_initialize(
    ^
libcaes_context.c:387:6: warning: comparison of function 'libcaes_context_initialize' equal to a null pointer is always false [-Wtautological-pointer-compare]
        if( libcaes_tables_initialized == 0 )
            ^~~~~~~~~~~~~~~~~~~~~~~~~~    ~
libcaes_context.c:387:6: note: prefix with the address-of operator to silence this warning
        if( libcaes_tables_initialized == 0 )
            ^
            &
libcaes_context.c:401:3: error: use of undeclared identifier 'libcaes_tables_initialized'
                libcaes_tables_initialized = 1;
                ^
libcaes_context.c:2941:5: error: implicit declaration of function 'libcaes_calculate_forward_table_round' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                                libcaes_calculate_forward_table_round(
                                ^
libcaes_context.c:2957:4: error: implicit declaration of function 'libcaes_calculate_forward_table_round' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        libcaes_calculate_forward_table_round(
                        ^
libcaes_context.c:2965:4: error: implicit declaration of function 'libcaes_calculate_forward_substitution_round' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        libcaes_calculate_forward_substitution_round(
                        ^
libcaes_context.c:2965:4: note: did you mean 'libcaes_calculate_forward_table_round'?
libcaes_context.c:2941:5: note: 'libcaes_calculate_forward_table_round' declared here
                                libcaes_calculate_forward_table_round(
                                ^
libcaes_context.c:2977:5: error: implicit declaration of function 'libcaes_calculate_reverse_table_round' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                                libcaes_calculate_reverse_table_round(
                                ^
libcaes_context.c:2993:4: error: implicit declaration of function 'libcaes_calculate_reverse_table_round' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        libcaes_calculate_reverse_table_round(
                        ^
libcaes_context.c:3001:4: error: implicit declaration of function 'libcaes_calculate_reverse_substitution_round' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        libcaes_calculate_reverse_substitution_round(
                        ^
libcaes_context.c:3001:4: note: did you mean 'libcaes_calculate_reverse_table_round'?
libcaes_context.c:2977:5: note: 'libcaes_calculate_reverse_table_round' declared here
                                libcaes_calculate_reverse_table_round(
                                ^
1 warning and 8 errors generated.

**Comment by joachimmetz** [comment]
Can you provide more context:

* what version are you trying to compile?
* are you using a source distribution package? or are you trying to build the source from git?
* add a copy of config.log

**Comment by srjavabeans** [comment]
I did the following:
```
 git clone https://github.com/libyal/libfsapfs.git
 cd libfsapfs/
 ./synclibs.sh
 ./autogen.sh
 ./configure
 make

```
here you are the config.log 
[config.log](https://github.com/libyal/libfsapfs/files/8007402/config.log)

**Comment by joachimmetz** [comment]
quickly scanned config.log 

```
pkg_cv_openssl_CFLAGS=-I/opt/local/libexec/openssl3/include
pkg_cv_openssl_LIBS='-L/opt/local/libexec/openssl3/lib -lssl -lcrypto'
```

openssl3 is not yet supported - https://github.com/libyal/libcaes/issues/17 - try building without openssl or the latest 1.1 version

**Comment by srjavabeans** [comment]
OK... and how do I exactly switch to the latest openssl 1.1 version?

**Comment by joachimmetz** [comment]
In that case it might be easier for you to build without openssl `./configure --with-openssl=no`

**Comment by srjavabeans** [comment]
Well I uninstall openssl 3.0, installed 1.1 and updated the symbolic link to the right version:
`
cd  /usr/local/include
ln -s  ../opt/openssl@1.1/include/openssl .
`

Still getting the same compilation error, maybe is just the version, is there one you consider more stable? 

just tried  `./configure --with-openssl=no  ` and OMG it did finish. 

Hopefully I can read the volume.

**Comment by joachimmetz** [comment]
> Still getting the same compilation error, maybe is just the version, is there one you consider more stable?

The CI compilation builds for Mac OS are passing so it is more likely something specific to your build environment.

> Hopefully I can read the volume.

We'll see, it looks like APFS can get corrupted in many different ways.

Seeing that the original question was answered closing issue.

**Comment by srjavabeans** [comment]
Hey Guys I did try to open a dmg file and got this: 

./fsapfsmount -f 1 /Volumes/RBackup/MM20220203.dmg got
fsapfsmount 20220201

Unable to open source container
libfsapfs_container_superblock_read_data: invalid object type: 0x00000000.
libfsapfs_container_superblock_read_file_io_handle: unable to read container superblock data.
libfsapfs_internal_container_open_read: unable to read container superblock at offset: 0 (0x00000000).
libfsapfs_container_open_file_io_handle: unable to read from file IO handle.
mount_handle_open: unable to open container.


Any clue?

**Comment by joachimmetz** [comment]
> Any clue?

yes, but that is outside the scope of this project do some research first about dmg files, volume systems and file systems.
