### ISSUE TITLE
unresolved external symbol for manual build of Dokan and fsapfsmount

### ISSUE THREAD

**Issue by smclinden** [libyal/libfsapfs#54]
So, admittedly, I am not Visual Studio/Microsoft expert.  And I am working in a Windows 11 Evaluation copy release that has proven exceedingly frustrating. So I am admitting that I don't know what I am doing,

I have downloaded the Dokan source code and successfully compiled it and it works.  I have added the paths to the local Dokan2 build source and release directories (using relative paths) and then successfully built fspafsmount but when I go to link it I get the error, above.

I was unable to successfully link to the Release install so this is a last ditch effort.

Thanks in advance, for any suggestions.

**Comment by joachimmetz** [comment]
why not use the provided visual studio project file?

**Comment by smclinden** [comment]
I did. I'm just building it in Visual Studio rather than MSBuild because I only have VC2019.

**Comment by joachimmetz** [comment]
>  I'm just building it in Visual Studio rather than MSBuild because I only have VC2019.

that should not matter, unless the conversion goes wrong.
why did you needed to add the paths then? 

The description of the issue hints something being wrong with the DLL import/export build configuration.

**Comment by smclinden** [comment]
I installed Dokan using the binary setup but Visual Studio did not find it at link time. So I downloaded the source and compiled Dokan, myself. With the root of the Dokan path the same as that of libfsapfs. With that I got closer in that the binary compiled but the linker didn't find the main which is odd because it is definitely in their.

If I try to run msbuild, I get the silly error related to VCTargets not being set (it looks for "Microsoft.Cpp.Default.props" at the root of "C:\" which means that something else was not set right. 

So I cannot compile at all with MSBUILD. I can compile with Visual Studio but not link.

**Comment by joachimmetz** [comment]
> If I try to run msbuild, I get the silly error related to VCTargets not being set (it looks for "Microsoft.Cpp.Default.props" at the root of "C:" which means that something else was not set right.

are you invoking msbuild under the VS initialized command prompt? are you invoking the right version of msbuild?
Have a look at https://github.com/libyal/libfsapfs/blob/main/build.ps1

> It could be the WINVER issue. I cannot find the hexadecimal value for WINVER in Windows 11 pre-production.

the description of the issue hints more at something wrong with the DLL import/export build configuration
* either the Dokan library does not export DokanMain as a DLL function
* or something is wrong with the import 

Try if building Dokan using https://github.com/libyal/libfsapfs/blob/main/builddokan.ps1 might addresses the issue

**Comment by smclinden** [comment]
That is the issue that I am having with the MSBuild, before. The vcvars64.bat does't set the correct variables.

'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat'
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.10
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
PS C:\Users\mclin\libfsapfs> .\builddokan.ps1
C:\\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe /verbosity:quiet /target:Build /property:Configuration=Release,Platform=x64 dokan\dokan.vcxproj
Microsoft (R) Build Engine version 4.8.9022.1
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

error MSB4019: The imported project "C:\Microsoft.cpp.Default.props" was not found.

**Comment by joachimmetz** [comment]
[Here](https://stackoverflow.com/questions/41695251/c-microsoft-cpp-default-props-was-not-found) is some context about `error MSB4019: The imported project "C:\Microsoft.cpp.Default.props" was not found.` looks like an issue in the build environment

Do not use `C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe` Try `C:\Program Files (x86)\Microsoft Visual Studio\2019\*\MSBuild\Current\Bin\MSBuild.exe` instead

**Comment by smclinden** [comment]
Yeah. I changed the build script to use that msbuild path.

Same issue. 


----- Original Message -----

**Comment by joachimmetz** [comment]
Not sure what is different about your build environment but e.g. the CI tests use this script https://ci.appveyor.com/project/libyal/libfsapfs/build/job/5m35dyxmuk8enqnt#L17
