### ISSUE TITLE
Unable to open a test DMG file created with APFS AES256

### ISSUE THREAD

**Issue by chrisnewmanuk** [libyal/libfsapfs#6]
Error when trying to fspafsinfo a dmg file (100Mb sample created on macos 10.13.4)

![libfsapfs_object_type_error](https://user-images.githubusercontent.com/7243321/53247732-0e145880-36ac-11e9-86d0-053bd5c4a700.png)

**Comment by joachimmetz** [comment]
1. make the sure the dmg is a raw (uncompressed), there are multiple types of dmg
2. a dmg typically contains a partition table, you need to point libfsapfs to the volume that contains APFS container

**Comment by chrisnewmanuk** [comment]
Ok.  The DMG was created on Mac 10.14 with the following settings: 100Mb size, AES256 Enc, Single GUID partition, APFS case sensitive.

I didnt see any option to deselected compression during the creation process?

Here is the DMG header - the rest of the data reads as 0x00 until offset 122386dec where the rest of the data to the end is the encrypted blob.

![image](https://user-images.githubusercontent.com/7243321/53256213-3c4f6380-36bf-11e9-86ce-75fa55abab45.png)

PWD for this is:    x

I have a couple of other tools that can open the DMG, crucially I wanted to try this library because of its similarities to the mounting process used by Bitlocker - providing decrypted block data "as a real block device" and being able to further mount it.

**Comment by joachimmetz** [comment]
> I have a couple of other tools that can open the DMG, crucially I wanted to try this library because of its similarities to the mounting process used by Bitlocker - providing decrypted block data "as a real block device" and being able to further mount it.

So this library will expose a file system, it will not exposes the container as a "raw" device (yet). Is on the wish list.

> I didnt see any option to deselected compression during the creation process?

Unfortunately the hexadecimal output does not provide me a hint about the image type.

Could you indicate how you created the dmg?

This might help me determine which "disk image type" https://github.com/libyal/libmodi/blob/master/documentation/Mac%20OS%20disk%20image%20types.asciidoc#1-overview

**Comment by joachimmetz** [comment]
No response from reporter closing issue.
