### ISSUE TITLE
libfsapfs_object_map_read_data: invalid object type: 0x00000000

### ISSUE THREAD

**Issue by KarelDemeyer** [libyal/libfsapfs#62]
fsapfstools are unable to read APFS container

libfsapfs_object_map_read_data: invalid object type: 0x00000000.
libfsapfs_object_map_read_file_io_handle: unable to read object map data.
libfsapfs_internal_container_open_read: unable to read object map at offset: 5550288896 (0x14ad2b000).
libfsapfs_container_open_file_io_handle: unable to read from file IO handle.
info_handle_open_input: unable to open input container.

[verbose_output.txt](https://github.com/libyal/libfsapfs/files/9307444/verbose_output.txt)

APFS image is in a E01-container imaged using dd of /dev/rdisk0 piped through ftkimager for mac

Using both fsapfsinfo 20220805 compiled from git today and fsapfsinfo 20190210 from Debian package.

Image taken from a Macbook Pro using OSX Monterey 12.3.1.

Kind regards

**Comment by joachimmetz** [comment]
look like your object map is empty

```
Reading object map:
libfsapfs_object_map_read_file_io_handle: reading object map at offset: 5550288896 (0x14ad2b000)
libfsapfs_object_map_read_data: object map data:
00000000: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
...
00000040: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000050: 00 00 00 00 00 00 00 00                            ........
```

**Comment by KarelDemeyer** [comment]
I believe the acquisition failed since in a new image, the volumes are recognised by fspafsinf
