### ISSUE TITLE
T2: cannot unlock volume (libfsapfs_internal_volume_unlock: invalid volume - missing key bag)

### ISSUE THREAD

**Issue by KarelDemeyer** [libyal/libfsapfs#63]
Cannot mount "Data volume" (Volume 5) in image of APFS container. Volume shows to be "locked" in fsapfsinfo. 

Known user password provided both with "-p" and "-r" flags. 

Unable to open source container
libfsapfs_internal_volume_unlock: invalid volume - missing key bag.
libfsapfs_volume_unlock: unable to unlock volume.
mount_handle_get_volume_by_index: unable to unlock volume.
mount_handle_open: unable to retrieve volume: 4.

[fsapfsmount_p5_output.txt](https://github.com/libyal/libfsapfs/files/9314873/fsapfsmount_p5_output.txt)
[fsapfsinfo_output.txt](https://github.com/libyal/libfsapfs/files/9314881/fsapfsinfo_output.txt)

**Comment by KarelDemeyer** [comment]
Likely this is due encryption in play? Image is from a 2021 Macbook pro (M1 chipset).
Is there a way to recognise this and update the output? 
Thanks for this great project

**Comment by joachimmetz** [comment]
does your macbook have a T2 chip?

**Comment by KarelDemeyer** [comment]
Indeed, the image is from a device with a T2 chip. I was too late to notice
this is not supported by libfsapfs. Please excuse me.

Is it even possible to support in future releases or is a needed secret
only available in the hardware? If possible to recognize the format, it
would be ideal if fsapfstools would report this.

Kind regards

Op vr 12 aug. 2022 20:54 schreef Joachim Metz ***@***.***>:

**Comment by joachimmetz** [comment]
> If possible to recognize the format, it would be ideal if fsapfstools would report this.

Which version of libfsapfs did you use? fsapfsinfo in the latest version should hint that T2 might be required.

> Is it even possible to support in future releases or is a needed secret only available in the hardware?

Hardware secret is needed.
