### ISSUE TITLE
pyfsapfs_test_container.py is missing in source package

### ISSUE THREAD

**Issue by vwegert** [libyal/libfsapfs#64]
Similar to [this](https://github.com/libyal/libfwnt/issues/12) and [this](https://github.com/libyal/libwrc/issues/1) issue: The file `tests/pyfsapfs_test_container.py` is present in the main Git repository, but missing in the released source packages. This causes the test to fail when run with `make check`. Manually adding the file from the master repository fixes the issue locally.

**Comment by joachimmetz** [comment]
Changes in https://github.com/libyal/libfsapfs/commit/ada46bb0bb9052d4ddd8abf7e5a7be1ca067e730
