### ISSUE TITLE
unable to makefile on mac

### ISSUE THREAD

**Issue by xtraa** [libyal/libfsapfs#66]
Hi, I followed your instructions and it's stiucked with

libcaes_context.c:31:10: fatal error: 'openssl/err.h' file not found

Not sure what to do. Sorry for being a noob.

**Comment by joachimmetz** [comment]
@xtraa this project is not intended for noobs, it assumes you know your way around building from source code. Regarding the issue you're encountering have a look at: https://github.com/libyal/libfsapfs/issues/56

**Comment by joachimmetz** [comment]
>  I just don't know how to point the compiler to the right direction.

have a look at `./configure --help` specifically the `--with-openssl` option

**Comment by joachimmetz** [comment]
have a look at verbose and debug output https://github.com/libyal/libfsapfs/wiki/Troubleshooting#verbose-and-debug-output

it will give you much detail about the format
