### ISSUE TITLE
How do I mount an APFS volume on a RAID?

### ISSUE THREAD

**Issue by rafacampoamor** [libyal/libfsapfs#67]
Hi!

I'm trying to mount an APFS encrypted drive, but I don't get which command to use. 
I've tried with :
`sudo fsapfsmount -f 1 -p PASSWORD /dev/sdb1 /mnt`

but got:
`Unable to open source container
libfsapfs_container_superblock_read_data: invalid object type: 0x00100020.
libfsapfs_container_superblock_read_file_io_handle: unable to read container superblock data.
libfsapfs_internal_container_open_read: unable to read container superblock at offset: 0 (0x00000000).
libfsapfs_container_open_file_io_handle: unable to read from file IO handle.
mount_handle_open: unable to open container.`

I've been looking around but couldn't get how to mount a RAID 

Anyone can help me?

**Comment by rafacampoamor** [comment]
Thanks!

It's a two SATA Drives mounted on a USB SATA Controller and made a JBOD APFS RAID with Apple's Disk Utility. It's totally functional on the Mac, but I don't know how to mount it on Ubuntu.

Doing a `lsblk`, I get:
```bash
sdb                8:16   0   2,7T  0 disk  
├─sdb1             8:17   0   200M  0 part  
├─sdb2             8:18   0   2,7T  0 part  
└─sdb3             8:19   0   128M  0 part  
sdc                8:32   0   2,7T  0 disk  
├─sdc1             8:33   0   200M  0 part  
├─sdc2             8:34   0   2,7T  0 part  
└─sdc3             8:35   0   128M  0 part  
```
Trying to get more details...
```bash
rafa@CampoaServer: fsapfsinfo sdb
fsapfsinfo 20201107

Unable to open: sdb.
libcfile_file_open_with_error_code: no such file: sdb.
libcfile_file_open: unable to open file.
libbfio_file_open: unable to open file: sdb.
libbfio_file_range_open: unable to open file IO handle.
libbfio_handle_open: unable to open handle.
libfsapfs_container_open_file_io_handle: unable to open file IO handle.
info_handle_open_input: unable to open input container.
```

```bash
fsapfsinfo sdb1
fsapfsinfo 20201107

Unable to open: sdb1.
libcfile_file_open_with_error_code: no such file: sdb1.
libcfile_file_open: unable to open file.
libbfio_file_open: unable to open file: sdb1.
libbfio_file_range_open: unable to open file IO handle.
libbfio_handle_open: unable to open handle.
libfsapfs_container_open_file_io_handle: unable to open file IO handle.
info_handle_open_input: unable to open input container.
```

```bash
fsapfsinfo sdc
fsapfsinfo 20201107

Unable to open: sdc.
libcfile_file_open_with_error_code: no such file: sdc.
libcfile_file_open: unable to open file.
libbfio_file_open: unable to open file: sdc.
libbfio_file_range_open: unable to open file IO handle.
libbfio_handle_open: unable to open handle.
libfsapfs_container_open_file_io_handle: unable to open file IO handle.
info_handle_open_input: unable to open input container.
```

```bash
fsapfsinfo sdc1
fsapfsinfo 20201107

Unable to open: sdc1.
libcfile_file_open_with_error_code: no such file: sdc1.
libcfile_file_open: unable to open file.
libbfio_file_open: unable to open file: sdc1.
libbfio_file_range_open: unable to open file IO handle.
libbfio_handle_open: unable to open handle.
libfsapfs_container_open_file_io_handle: unable to open file IO handle.
info_handle_open_input: unable to open input container.
```

Any ideas?

**Comment by joachimmetz** [comment]
libfsapfs only works on the partition that contains the APFS container. So `fsapfsinfo sdc` makes no sense.

Regarding `libcfile_file_open_with_error_code: no such file: sdc1.` try opening `/dev/sdc1` (the correct path) with the necessary permissions (like as root)

However since this is a RAID set you (likely) need to reconstruct that first and run libfsapfs on the resulting RAID volume.

**Comment by rafacampoamor** [comment]
Much of the same thing...

```bash
sudo fsapfsinfo /dev/sdc1
[sudo] contraseña para rafa: 
fsapfsinfo 20201107

Unable to open: /dev/sdc1.
libfsapfs_container_superblock_read_data: invalid object type: 0x00100020.
libfsapfs_container_superblock_read_file_io_handle: unable to read container superblock data.
libfsapfs_internal_container_open_read: unable to read container superblock at offset: 0 (0x00000000).
libfsapfs_container_open_file_io_handle: unable to read from file IO handle.
info_handle_open_input: unable to open input container.
```

**Comment by joachimmetz** [comment]
I repeat **However since this is a RAID set you (likely) need to reconstruct that first and run libfsapfs on the resulting RAID volume.**

**Comment by rafacampoamor** [comment]
Ok! Any suggestion to do that without formatting the disk or lose any data? 

Thanks!!

**Comment by joachimmetz** [comment]
is "Apple RAID" compatible with linux software RAID ?

**Comment by joachimmetz** [comment]
"Apple RAID" is out of scope of this project, closing.
