### ISSUE TITLE
fsapfsmount: unable to retrieve volume: 0

### ISSUE THREAD

**Issue by mifanj** [libyal/libfsapfs#68]
### System environment
> macOS 13.3.1 (22E261)

Hi, I got an error by

`sudo fsapfsmount -v /dev/disk /point_path`

short error was

```
fsapfsmount 20230322

Unable to open source container
libfsapfs_container_get_volume_by_index: unable to retrieve object map descriptor for volume object identifier: 0.
mount_handle_get_volume_by_index: unable to retrieve volume: 0.
mount_handle_open: unable to retrieve volume: 0.
```

longer error start with
```
fsapfsmount 20230322

libcfile_internal_file_get_size: block size: 512 block count: 489482200 libcfile_internal_file_get_size: device media size: 250614886400
Reading container superblock:
libfsapfs_container_superblock_read_file_io_handle: reading container superblock at offset: 0 (0x00000000)
```

full output in this log file [output.log](https://github.com/libyal/libfsapfs/files/11197178/output.log)

Is there any chance to retrieve my data in this hard drive?  T_T

**Comment by mifanj** [comment]
I retry by `-f` command to specify volume of container

when `-f 0`  [f0out.log](https://github.com/libyal/libfsapfs/files/11206568/f0out.log)
I got 2 more lines output
```
mount_handle_set_file_system_index: invalid file system index value out of bounds.
Unsupported file system index defaulting to: all.
```
I think it seems like a nonsupport argument value


then `-f 1`  [f1out.log](https://github.com/libyal/libfsapfs/files/11206576/f1out.log)
output just as same as no `-f` command

then `-f 2`  [f2out.log](https://github.com/libyal/libfsapfs/files/11206578/f2out.log)
output is missing a few lines

then `-f 3`  [f3out.log](https://github.com/libyal/libfsapfs/files/11206639/f3out.log)
output just as same as `-f 2` command

then `-f 4` is as same as `-f 2` too
and so on...

**Comment by joachimmetz** [comment]
what does fsapfsinfo tell you about the container layout?

**Comment by joachimmetz** [comment]
No response from original reporter closing issue.
