### ISSUE TITLE
trying to build it under macOS 11.7.4 (BigSur) - 'openssl/err.h' file not found

### ISSUE THREAD

**Issue by chriskuku** [libyal/libfsapfs#69]
`libcaes_context.c:31:10: fatal error: 'openssl/err.h' file not found
#include <openssl/err.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [libcaes_context.lo] Error 1
make: *** [all-recursive] Error 1
$ 
`
to no avail.

**Comment by joachimmetz** [comment]
make sure to set up openssl on your build system and ensure configure knows about the proper path, or try compiling without openssl support. See previous closed issue for similar advice.
