### ISSUE TITLE
Update README to markdown by renaming to README.md

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [libyal/libfsapfs#70]
Two things:
1. [ ] Update README to markdown by renaming to README.md This would beautify it. 
1. [ ] Also, add a note in the readme on how this project differs from, is better or worse then, etc, `apfs-fuse`: https://github.com/sgan81/apfs-fuse

**Comment by joachimmetz** [comment]
> Also, add a note in the readme on how this project differs from, is better or worse then, etc, apfs-fuse: https://github.com/sgan81/apfs-fuse

Why? This is not a competition.

> Update README to markdown by renaming to README.md This would beautify it.

No, what about systems that don't support Markdown?

**Comment by ElectricRCAircraftGuy** [comment]
> Why? This is not a competition.

As I'm trying to figure out which tools exist, how to use them, and how well they work, it's useful to get my bearings. I asked @eafer the same question here ([Please mention a list of alternative APFS mount tools, and the pros and cons of each, if you are aware of any](https://github.com/linux-apfs/linux-apfs-rw/issues/42)), and they [gave an excellent summary](https://github.com/linux-apfs/linux-apfs-rw/issues/42#issuecomment-1548859155). That is very helpful.

 > No, what about systems that don't support Markdown?

There's no such thing! GitHub is what renders the markdown into HTML. Your repo is on GitHub. *All* computers can access GitHub through a browser, so *all* support Markdown. Your README is _already written in Markdown_, you just don't even realize it. Here's what it looks like on GitHub if you just rename your readme from `README` to `README.md`: https://github.com/ElectricRCAircraftGuy/libfsapfs

Before:

![image](https://github.com/libyal/libfsapfs/assets/6842199/77c06b03-7c3d-4f3c-ac90-5698bae0b7de)

After:

![image](https://github.com/libyal/libfsapfs/assets/6842199/bcfbe01c-7859-45f2-ac11-6f00abf1fe08)

Here's my commit that did that. I've opened a PR for you: https://github.com/libyal/libfsapfs/pull/71

**Comment by joachimmetz** [comment]
> There's no such thing. 

There are plenty. Markdown is a formatting language (see: https://en.wikipedia.org/wiki/Markdown), if you don't have a fomatter, it is just plain text. Also there are many different slight variations of Markdown

> As I'm trying to figure out which tools exist, how to use them, and how well they work, it's useful to get my bearings.

Why does this project need to provide a comparison then? Why is the information in the README not sufficient for you?

**Comment by ElectricRCAircraftGuy** [comment]
> if you don't have a fomatter, it is just plain text. 

GitHub.com is the formatter. That's the point. Of course it's just plain text otherwise. People don't need a markdown viewer. IF you rename the file, like 99% of other readmes on GitHub have, GitHub will render it properly when people view it online at https://github.com/libyal/libfsapfs. 

I am so glad I don't work with you.

**Comment by joachimmetz** [comment]
> GitHub.com is the formatter.

This file is distributed in the source package, that does not contain the GitHub Markdown formatter does it?

**Comment by joachimmetz** [comment]
> I am so glad I don't work with you.

Why do have to behave like a jerk?
