### ISSUE TITLE
`./autogen.sh` error: `configure.ac:1: error: Autoconf version 2.71 or higher is required`

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [libyal/libfsapfs#72]
I'm on Linux Ubuntu 20.04. I'm looking at your instructions here: https://github.com/libyal/libfsapfs/wiki/Building

I'd like to test your project to see if it works to mount my Apple APFS filesystem on an old MacBook I'm repairing, but I don't know how. I ran this:
```bash
sudo apt install git autoconf automake autopoint libtool pkg-config gettext

git clone https://github.com/libyal/libfsapfs.git
cd libfsapfs/
./synclibs.sh
./autogen.sh
```

I got this error: 
```bash
libfsapfs$ ./autogen.sh
autopoint: *** The AM_GNU_GETTEXT_VERSION declaration in your configure.ac
               file requires the infrastructure from gettext-0.21 but this version
               is older. Please upgrade to gettext-0.21 or newer.
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
```

So I updated `gettext` per my instructions here: https://askubuntu.com/a/1468793/327339

Now I get this error:

```bash
libfsapfs$ ./autogen.sh 
configure.ac:1: error: Autoconf version 2.71 or higher is required
configure.ac:1: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: error: echo failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
```

So I updated `autoconf` per my instructions here: https://askubuntu.com/a/1468799/327339

I now have this version:
```bash
libfsapfs$ autoconf --version
autoconf (GNU Autoconf) 2.71
```

...yet I still get the error above saying `Autoconf version 2.71 or higher is required`. 

What am I missing? Thanks in advance for your help.

**Comment by joachimmetz** [comment]
Why should I help you? Especially after you were clear you don't want to work with me in https://github.com/libyal/libfsapfs/issues/70#issuecomment-1556110641 I cite `I am so glad I don't work with you.`

**Comment by ElectricRCAircraftGuy** [comment]
> Why should I help you? Especially after you were clear you don't want to work with me in [#70 (comment)](https://github.com/libyal/libfsapfs/issues/70#issuecomment-1556110641) I cite `I am so glad I don't work with you.`

Because anyone on Ubuntu 20.04 will have this problem, and that is a large population. By helping me, you're helping others, and making your project more successful and more accessible to the world.

**Comment by ElectricRCAircraftGuy** [comment]
Also, people can read our thread to see how antagonistic you were from the start, when I was just trying to help. Let them look at how I've interacted with people on my projects vs how you've interacted on yours, and be their own judge of who they might want to work with. I find a tremendous value in helping others, and trying to be kind in my interactions so that I can help them learn and grow from me, so I can learn and grow from them, and so we can grow and improve together. When I have valuable knowledge, I naturally want others to have it as well.

https://github.com/libyal/libfsapfs/issues/70

**Comment by joachimmetz** [comment]
> Because it is likely that anyone on Ubuntu 20.04 will have this problem, and that is a large population.

See: https://github.com/libyal/libfsapfs/wiki/Building#read-first Ubuntu 20.04 is not supposed to use the WIP git HEAD version. If you want to develop on this project use an up to date autoconf version.

> Also, people can read https://github.com/libyal/libfsapfs/issues/70 to see how antagonistic you were from the start, when I was just trying to help.

That is your interpretation, my interpretation is that you are not being helpful at all, only egocentric stating how you want things to be.

> and trying to be kind in my interactions 

Yeah that is very clear from `I am so glad I don't work with you.`

**Comment by ElectricRCAircraftGuy** [comment]
Hopefully someone else stumbles upon this thread and documents their solution to it. 

If not though, to anyone else who can't figure out how to get `libfsapfs` to build, I recommend you try `[linux-apfs-rw](https://github.com/linux-apfs/linux-apfs-rw)` instead. It builds easily, and has a really kind maintainer, as you can see from this thread: https://github.com/linux-apfs/linux-apfs-rw/issues/42. And, I've documented my full build instructions for it on an Ubuntu 22.04 live USB, here: https://github.com/linux-apfs/linux-apfs-rw/issues/42#issuecomment-1556103266

See also this Q&A: [Super User: How to mount APFS on Linux or Windows?](https://superuser.com/q/1267291/425838)
