### ISSUE TITLE
Unable to run fsapfsinfo with Operation not permitted

### ISSUE THREAD

**Issue by CraigAnderson8** [libyal/libfsapfs#75]
Running _fsapsfinfo_ on an unmounted disk always give me:
`Unable to open: /dev/disk3.
libcfile_file_open_with_error_code: unable to open file: /dev/disk3 with error: Operation not permitted`

I gave full disk permission in the Security and Privacy settings.  Also running as root.  Tried compiling a static binary - it did not help.

System is running macOS Monterey.

**Comment by joachimmetz** [comment]
Is the APFS container mounted?

**Comment by CraigAnderson8** [comment]
Th APFS container is not mounted.

Regards,

Craig

**Comment by joachimmetz** [comment]
Craig, I current don't have time for a question-answer debugging session. `Operation not permitted` indicates that your system configuration does not allow you to access to `/dev/disk3`. This is an issue specific to your set up, without necessary details, I cannot help you with that. I'll close this issue for now.
