### ISSUE TITLE
How do I give a standard or admin user access?

### ISSUE THREAD

**Issue by hstriepe** [libyal/libfsapfs#78]
Thanks for the work.
This works for me for ZorinOS using sudo. How do I give a standard or admin user access?

**Comment by joachimmetz** [comment]
what backed are you using? fuse or dokan?

**Comment by hstriepe** [comment]
Fuse.

**Comment by joachimmetz** [comment]
@hstriepe What have you tried? what is your fuse configuration?. Can you please be a bit more verbose and proactive in your communication. I don't have the time to do extensive a back and forth debugging sessions with you. 

Have a look at your fuse configuration, which options you can configure it with the `-X` option. 

Also have a look at https://github.com/libyal/libfsapfs/wiki/Mounting

Closing this, given the wiki article should give you enough context to figure it out yourself.
