### ISSUE TITLE
Unable to use libfsapfs on iPhone 5S image with no Cydia installed?

### ISSUE THREAD

**Issue by pmo-19** [libyal/libfsapfs#8]
Error

**Comment by joachimmetz** [comment]
@pmo-19 can you be more descriptive in what does not work? Note that this project is experimental and can only improve if you provide more details.

* Can you provide a test image?
* Can you provide debug output (https://github.com/libyal/libfsapfs/wiki/Troubleshooting#verbose-and-debug-output)?

**Comment by pmo-19** [comment]
Sorry I reported a bug on your GitHub project by error. I miss selected the browser tab.
This was to be reported on another GitHub project.
Please delete everything.

**Comment by joachimmetz** [comment]
> Please delete everything.

@pmo-19 FYI github does not support deleting issues.
