### ISSUE TITLE
Unable to set container offset.

### ISSUE THREAD

**Issue by lucyamonster** [libyal/libfsapfs#80]
when I run: `sudo fsapfsmount -v /dev/sdc /mnt -o nonempty`
I get this error:

> fsapfsmount 20201107
> 
> Unable to set container offset.
> mount_handle_system_string_copy_from_64_bit_in_decimal: unsupported character value: n at index: 0.
> mount_handle_set_offset: unable to copy string to 64-bit decimal.

I'm completely new to this tool and I haven't found anything about this error. Is there something stupid that I forgot?
Thanks in advance for your help

**Comment by joachimmetz** [comment]
That's because you are setting offset (-o) to nonempty

**Comment by lucyamonster** [comment]
without `-o nonempty` I get
> fsapfsmount 20201107
> 
> fuse: mountpoint is not empty
> fuse: if you are sure this is safe, use the 'nonempty' mount option
> Unable to create fuse channel.

and I thought `-o nonempty` is how to get around this error?:
> fsapfsmount 20201107
> 
> fuse: mountpoint is not empty
> fuse: if you are sure this is safe, use the 'nonempty' mount option
> Unable to create fuse channel.

**Comment by joachimmetz** [comment]
this is not an error, you are providing with -o nonsensical input. Read the link I pointed out earlier, it provides you with examples.

**Comment by joachimmetz** [comment]
> fuse: if you are sure this is safe, use the 'nonempty' mount option

this is a warning of you fuse backend, make sure to configure it correctly or use -X to pass back-end (in this case fuse) options.

**Comment by joachimmetz** [comment]
Also mounting on a non-empty mount point is not recommended practice.
